### ISSUE TITLE
大型认亲现场

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#105]
### Describe the bug

I have no problems but I want to be in this project

### The log file and images/videos

I want to be in this project

### Steps To Reproduce

```markdown
I want to be in this project
```

### Expected Behavior

I have no problem but I want to be in this project

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
No problem
```

### Anything else?

I have a no problem but I want to be in this project

**Comment by Vera-Firefly** [comment]
Give a reason why you can join, such as what programming language you know.

**Comment by kjjjjjjjjjjjj** [comment]
Can you please my sister I don't know do you like to me to say you sister please my sister please give me a Chan

**Comment by Vera-Firefly** [comment]
> Can you please my sister I don't know do you like to me to say you sister please my sister please give me a Chan

what‽ sister?!

**Comment by Vera-Firefly** [comment]
> > Can you please my sister I don't know do you like to me to say you sister please my sister please give me a Chan
> 
> what‽ sister?!

What your mean?

**Comment by kjjjjjjjjjjjj** [comment]
My mean is do you like me to say you sister

**Comment by kjjjjjjjjjjjj** [comment]
Hello sister do you hear me

**Comment by Vera-Firefly** [comment]
> Hello sister do you hear me

So what's your purpose?

**Comment by kjjjjjjjjjjjj** [comment]
My problem is to I need to be in your project my problem is this thank you sister

**Comment by Vera-Firefly** [comment]
> My problem is to I need to be in your project my problem is this thank you sister

Participate in this project?
What can you do?
java , C or CPP?

**Comment by kjjjjjjjjjjjj** [comment]
Java

**Comment by Vera-Firefly** [comment]
> Java

Really?

**Comment by Vera-Firefly** [comment]
Wait wait wait

**Comment by Vera-Firefly** [comment]
> Wait wait wait

If you simply want to contribute to the repository or compile it yourself, you can fork it
Why do you have to join it?

**Comment by kjjjjjjjjjjjj** [comment]
Yes I have to join it and  I can provide you with Java programs, etc. You just need to insert them into the app; that's your task.

**Comment by kjjjjjjjjjjjj** [comment]
I give a computer for repairing

**Comment by Vera-Firefly** [comment]
> Yes I have to join it and I can provide you with Java programs, etc. You just need to insert them into the app; that's your task.

You can modify it yourself after fork and submit a PR after completion.

**Comment by kjjjjjjjjjjjj** [comment]
ok but please I request to join it I have not project

**Comment by kjjjjjjjjjjjj** [comment]
And talk with you I have a better sister

**Comment by Vera-Firefly** [comment]
> ok but please I request to join it I have not project

I have a question, do you really understand what I said?

**Comment by kjjjjjjjjjjjj** [comment]
Yes I understand what you said so what is the question

**Comment by kjjjjjjjjjjjj** [comment]
I will help you in Java

**Comment by Vera-Firefly** [comment]
> I will help you in Java

If it is convenient, can you tell me what country you are from?

**Comment by kjjjjjjjjjjjj** [comment]
I am from Pakistan and my city is Karachi

**Comment by kjjjjjjjjjjjj** [comment]
First I get a hmcl but I told the creators to I need for Android 7.0 but no one give me the Android 7.0 version of hmcl so I am angry to creators of hmcl so please can I join in your project

**Comment by Vera-Firefly** [comment]
> I am from Pakistan and my city is Karachi

Oky , my email address is verafirefly0515@outlook.com , If you can't reach me on Github, you can email me.

**Comment by Vera-Firefly** [comment]
> > I am from Pakistan and my city is Karachi
> 
> Oky , my email address is [verafirefly0515@outlook.com](mailto:verafirefly0515@outlook.com) , If you can't reach me on Github, you can email me.

As far as joining this repository, it may not be possible, but I can pull you into another repository.

**Comment by kjjjjjjjjjjjj** [comment]
Thank you my sister I am so feeling fresh to meet with you and talk with you

**Comment by kjjjjjjjjjjjj** [comment]
And please join me in your project

**Comment by Vera-Firefly** [comment]
> And please join me in your project

https://github.com/Vera-Firefly/PojavLauncher-Experimental-Edition

**Comment by kjjjjjjjjjjjj** [comment]
But how do I join

**Comment by kjjjjjjjjjjjj** [comment]
I accepted but I don't see in creators

**Comment by Vera-Firefly** [comment]
> I accepted but I don't see in creators

emm.

**Comment by kjjjjjjjjjjjj** [comment]
I accepted thank you my sister thank you you are a most beautiful friend and you are nice to

**Comment by Vera-Firefly** [comment]
> I accepted thank you my sister thank you you are a most beautiful friend and you are nice to

Have a good cooperation

**Comment by kjjjjjjjjjjjj** [comment]
You are my good cooperation

**Comment by Vera-Firefly** [comment]
> You are my good cooperation

I suggest you learn how to use Github.

**Comment by Vera-Firefly** [comment]
> > You are my good cooperation
> 
> I suggest you learn how to use Github.

Compile locally before you know how to submit PR.

**Comment by kjjjjjjjjjjjj** [comment]
Sorry if I say something wrong

**Comment by kjjjjjjjjjjjj** [comment]
I said you are my best competitor my mean is that but I have a spelling issues

**Comment by kjjjjjjjjjjjj** [comment]
If I say something wrong sorry my sister

**Comment by Vera-Firefly** [comment]
> I said you are my best competitor my mean is that but I have a spelling issues

what‽Competitors?

**Comment by kjjjjjjjjjjjj** [comment]
You are my best sister and my best competitor and best friend also

**Comment by kjjjjjjjjjjjj** [comment]
If I have some mistakes so say me to I apologize you

**Comment by Vera-Firefly** [comment]
Let me see. Competitor?It's time for me to consider the reasonableness of letting you in.

**Comment by kjjjjjjjjjjjj** [comment]
Sorry if I something say wrong I really really apologizing to you my sister

**Comment by Vera-Firefly** [comment]
Again, if you want to compile it yourself, you can choose to compile it locally.

**Comment by kjjjjjjjjjjjj** [comment]
And the app is banned on Play Store so I cannot in toilet so sorry

**Comment by Vera-Firefly** [comment]
> Again, if you want to compile it yourself, you can choose to compile it locally.

If you want to contribute to the Pojav Beta · Zink app, you can modify it after fork and then submit PR.

**Comment by Vera-Firefly** [comment]
> And the app is banned on Play Store so I cannot in toilet so sorry

Why didn't you choose to modify PojavLauncher?

**Comment by kjjjjjjjjjjjj** [comment]
Not this time but I can my computer is going for repairing so not this time but my after repairing I can install Android studio and upgrade the app

**Comment by Vera-Firefly** [comment]
> > And the app is banned on Play Store so I cannot in toilet so sorry
> 
> Why didn't you choose to modify PojavLauncher?

I'm not the original author, this app, it's forked from PojavLauncherTeam.

**Comment by kjjjjjjjjjjjj** [comment]
Yes I know

**Comment by Vera-Firefly** [comment]
> Yes I know

So?Why didn't you choose to go to PojavLauncherTeam?
https://github.com/PojavLauncherTeam/PojavLauncher

**Comment by kjjjjjjjjjjjj** [comment]
Yes yes I see

**Comment by kjjjjjjjjjjjj** [comment]
And say me my sister what can I do for you

**Comment by kjjjjjjjjjjjj** [comment]
Talk on email my sister

**Comment by Vera-Firefly** [comment]
> And say me my sister what can I do for you
I have done what I have to do here, so I don't need to do anything for the time being.

**Comment by Vera-Firefly** [comment]
> Talk on email my sister

Oky

**Comment by kjjjjjjjjjjjj** [comment]
Sorry to say I am with my guess so we can talk later

**Comment by kjjjjjjjjjjjj** [comment]
Yes I am on email now I download the app and message you on email so answer
