### ISSUE TITLE
World crashing bug

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#109]
### Describe the bug

I download mod pack but world's as crushing what can I do I try everything

### The log file and images/videos

This is my personal tips first check the all code and run coding if you face a error code change it so your game will be good and please check the Java code and run it and read your App all code thank you this is my personal tips and this is help you in a great Java

### Steps To Reproduce

```markdown
<!-- pom.xml file -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>your.group.id</groupId>
    <artifactId>your-artifact-id</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source> <!-- Set your current Java version -->
        <maven.compiler.target>1.8</maven.compiler.target> <!-- Set your current Java version -->
    </properties>

    <!-- Add other dependencies and configuration as needed -->

</project>
```

### Expected Behavior

So this is a code I give you try it and upgrade your Java

### Platform

```markdown
- Device model: Samsung Galaxy
- CPU architecture:
- Android version: 7.0
- PojavLauncher version: latest version
```

### Anything else?

Please I give you tips I give you a code please I give you everything to fix it and every tips I give you please fix it I love to play

**Comment by Vera-Firefly** [comment]
> ### Describe the bug
> I download mod pack but world's as crushing what can I do I try everything
> 
> ### The log file and images/videos
> This is my personal tips first check the all code and run coding if you face a error code change it so your game will be good and please check the Java code and run it and read your App all code thank you this is my personal tips and this is help you in a great Java
> 
> ### Steps To Reproduce
> ```
> 
> 
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
> 
>     <groupId>your.group.id</groupId>
>     <artifactId>your-artifact-id</artifactId>
>     <version>1.0.0</version>
> 
>     <properties>
>         <maven.compiler.source>1.8</maven.compiler.source> 
>         <maven.compiler.target>1.8</maven.compiler.target> 
>     </properties>
> 
>     
> 
> </project>
> ```
> 
> ### Expected Behavior
> So this is a code I give you try it and upgrade your Java
> 
> ### Platform
> ```
> - Device model: Samsung Galaxy
> - CPU architecture:
> - Android version: 7.0
> - PojavLauncher version: latest version
> ```
> 
> ### Anything else?
> Please I give you tips I give you a code please I give you everything to fix it and every tips I give you please fix it I love to play

You don't have any punctuation marks with you, which makes it a little difficult for me to distinguish what you're saying. Do you mean to let me upgrade Java?

**Comment by kjjjjjjjjjjjj** [comment]
Thank you so much to reply me sister

**Comment by kjjjjjjjjjjjj** [comment]
yes
________________________________
