### ISSUE TITLE
[BUG] <Short description>I can't operation minecraft(1.18.2))

### ISSUE THREAD

**Issue by xguan744** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#138]
### Describe the bug

When entering the game popup code 1 exit
![Screenshot_20240223_102715_net kdt pojavlaunch firefly_edit_1506584658083131](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/128487904/e707ac5c-95b2-448a-8176-61161d6b338b)

### The log file and images/videos

[latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/14381108/latestlog.txt)

### Steps To Reproduce

```markdown
no
```

### Expected Behavior

I hope I can play Minecraft

### Platform

```markdown
- Device model: HONOR 9X PRO 6/64G
- CPU architecture: aarch
- Android version: 10
- PojavLauncher version: edelweiss-20240221-56833ec-exp_v3
```

**Comment by Vera-Firefly** [comment]
You can try this https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8013896376
