### ISSUE TITLE
move game dir to /sdcard/games

### ISSUE THREAD

**Issue by hyplant** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#140]
把游戏目录移至内部存储。

Move Game Dir to `/sdcard/games/pojav`, like the older pojav launcher. This makes it easier to access the game files.

把游戏目录移动到`/sdcard/games/pojav`，就像旧的pojav那样。这样访问游戏文件更方便。

**Comment by Vera-Firefly** [comment]
> 把游戏目录移至内部存储。
> 
> Move Game Dir to `/sdcard/games/pojav`, like the older pojav launcher. This makes it easier to access the game files.
> 
> 把游戏目录移动到`/sdcard/games/pojav`，就像旧的pojav那样。这样访问游戏文件更方便。

后面会有一个公有,私有目录选择,我还在确定方案

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/pull/235
