### ISSUE TITLE
[BUG] <Short description>无法安装forge

### ISSUE THREAD

**Issue by xguan744** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#144]
### Describe the bug

无法使用安装器安装forge 1.16.5

### The log file and images/videos

https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/128487904/aeae1917-e168-4265-9eab-a4aed16ecd4f

[latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/14421568/latestlog.txt)

### Steps To Reproduce

```markdown
无
```

### Expected Behavior

我希望可以正常使用

### Platform

```markdown
- Device model: oppo k9
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20240223-edd0fb2-exp
```

**Comment by Vera-Firefly** [comment]
待Pojav团队修

**Comment by xguan744** [comment]
> 待Pojav团队修

这么说pojav团队知道这个问题吗

**Comment by Vera-Firefly** [comment]
或许你可以尝试一下使用启动器自带的自动安装器

**Comment by Vera-Firefly** [comment]
安装.jar你必须使用java8去运行才能正常工作,除某些需要java17的装载器外都是用的java8
