### ISSUE TITLE
[suggestion] add holy Gl4Es v3.2

### ISSUE THREAD

**Issue by ItsWinterBush26** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#147]
add opengle3.2 and labymod ,sodium support

**Comment by kwssdme** [comment]
这是真的？

**Comment by Vera-Firefly** [comment]
Wait for the new gl4es to appear

**Comment by Vera-Firefly** [comment]
Does not appear to be feasible, custom LIBGL_GL does not appear to be valid
