### ISSUE TITLE
[Add render] <Mesa LLVMpipe>

### ISSUE THREAD

**Issue by Natthakritp** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#156]
### Describe the bug

-

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
- Device model: -
- CPU architecture: -
- Android version: -
- PojavLauncher version: -
```

### Anything else?

Added rendering of Mesa LLVMpipe and the latest version of Mesa.

**Comment by Natthakritp** [comment]
Is it possible to add PowerVR renderer?

https://docs.mesa3d.org/drivers/powervr.html

**Comment by Vera-Firefly** [comment]
I'll think about it

**Comment by Vera-Firefly** [comment]
These two days plus, Mesa versions: 23.0.4 and 23.0.0-devel

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850

**Comment by WesleyVanNeck** [comment]
> https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850

Llvm pipe still doesn't work

**Comment by WesleyVanNeck** [comment]
[latestlog (1).txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/14666556/latestlog.1.txt)

**Comment by Natthakritp** [comment]
Llvm pipe still doesn't work

**Comment by WesleyVanNeck** [comment]
Soft pipe works

**Comment by Vera-Firefly** [comment]
> > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> 
> Llvm pipe still doesn't work

It only runs on x86 or amd64 architectures, and I didn't complete the library.

**Comment by WesleyVanNeck** [comment]
> > > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> > 
> > 
> > Llvm pipe still doesn't work
> 
> It only runs on x86 or amd64 architectures, and I didn't complete the library.

Pls complete it so it runs on arm

**Comment by Vera-Firefly** [comment]
I will complete all the libraries later

**Comment by WesleyVanNeck** [comment]
Also why does it work on my arm Chromebook running linux

> I will complete all the libraries later

It does run arm64 right I mean it works on my arm Chromebook running linux

**Comment by Vera-Firefly** [comment]
> > > > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> > > 
> > > 
> > > Llvm pipe still doesn't work
> > 
> > 
> > It only runs on x86 or amd64 architectures, and I didn't complete the library.
> 
> Pls complete it so it runs on arm

you can use softpipe, llvmpipe is on runs on x86 or amd64, 64-bits

**Comment by WesleyVanNeck** [comment]
> > > > > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> > > > 
> > > > 
> > > > Llvm pipe still doesn't work
> > > 
> > > 
> > > It only runs on x86 or amd64 architectures, and I didn't complete the library.
> > 
> > 
> > Pls complete it so it runs on arm
> 
> you can use softpipe, llvmpipe is on runs on x86 or amd64, 64-bits

Why does it runn on my arm linix machine

**Comment by WesleyVanNeck** [comment]
Then

**Comment by Vera-Firefly** [comment]
what‽

**Comment by Vera-Firefly** [comment]
> > > > > > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> > > > > 
> > > > > 
> > > > > Llvm pipe still doesn't work
> > > > 
> > > > 
> > > > It only runs on x86 or amd64 architectures, and I didn't complete the library.
> > > 
> > > 
> > > Pls complete it so it runs on arm
> > 
> > 
> > you can use softpipe, llvmpipe is on runs on x86 or amd64, 64-bits
> 
> Why does it runn on my arm linix machine

Let me have a look

**Comment by Vera-Firefly** [comment]
Can you provide it? Thank you

**Comment by WesleyVanNeck** [comment]
> > > > > > > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> > > > > > 
> > > > > > 
> > > > > > Llvm pipe still doesn't work
> > > > > 
> > > > > 
> > > > > It only runs on x86 or amd64 architectures, and I didn't complete the library.
> > > > 
> > > > 
> > > > Pls complete it so it runs on arm
> > > 
> > > 
> > > you can use softpipe, llvmpipe is on runs on x86 or amd64, 64-bits
> > 
> > 
> > Why does it runn on my arm linix machine
> 
> Let me have a look

Well it's available for a raspberry pi 3 and thats arm https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://forums.raspberrypi.com/viewtopic.php%3Ft%3D338600&ved=2ahUKEwjSgv6n74KFAxVvwQIHHZAzDEoQFnoECA0QAQ&usg=AOvVaw0KNl4JaNYCiM-xFwiu7M0P

**Comment by Vera-Firefly** [comment]
> > > > > > > > https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8357381850
> > > > > > > 
> > > > > > > 
> > > > > > > Llvm pipe still doesn't work
> > > > > > 
> > > > > > 
> > > > > > It only runs on x86 or amd64 architectures, and I didn't complete the library.
> > > > > 
> > > > > 
> > > > > Pls complete it so it runs on arm
> > > > 
> > > > 
> > > > you can use softpipe, llvmpipe is on runs on x86 or amd64, 64-bits
> > > 
> > > 
> > > Why does it runn on my arm linix machine
> > 
> > 
> > Let me have a look
> 
> Well it's available for a raspberry pi 3 and thats arm https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://forums.raspberrypi.com/viewtopic.php%3Ft%3D338600&ved=2ahUKEwjSgv6n74KFAxVvwQIHHZAzDEoQFnoECA0QAQ&usg=AOvVaw0KNl4JaNYCiM-xFwiu7M0P

But the problem is that that build is only available for x86 or amd64

**Comment by WesleyVanNeck** [comment]
![2024-03-21-18-17-52-684](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/25864932/f2612393-a750-4a99-a26d-b291bc568141)
![2024-03-21-18-21-48-306](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/25864932/9ab6cc2d-56f1-45f1-a87b-355edaae162b)

But what do you mean by that because I got it working on linux on a arm system @Vera-Firefly

**Comment by Vera-Firefly** [comment]
Maybe I'm forgetting something, llvmpipe doesn't work
