### ISSUE TITLE
[enhancement] <Mesa Zink for Vulkan 1.1>

### ISSUE THREAD

**Issue by Natthakritp** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#157]
### Describe the bug

-

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
- Device model: Samsung Galaxy A12 128/4G
- CPU architecture: Arm64 Helio P35(PowerVR Rogue GE8320)
- Android version: 12
- Vulkan version: 1.1.131
- Vulkan driver version: 1.386.1368
- Vulkan device: PowerVR Rogue GE8320
- PojavLauncher version: edelweiss-20240309-1dbb531-exp_v3 (Release)
```

### Anything else?

Added the latest version of Mesa Zink that supports Vulkan 1.1.131.Tried version 22.0.5 and it works.

**Comment by Vera-Firefly** [comment]
Does Mesa 23.0.4 not work?

**Comment by Vera-Firefly** [comment]
![Screenshot_2024_0310_085259](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/22aaab17-051d-4530-9e36-580867a235a2)
![Screenshot_2024_0310_085408](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/6507cddf-75b4-4ac4-9aa4-9a1ead45f0a6)
Your device doesn't seem to support it

**Comment by Natthakritp** [comment]
> Does Mesa 23.0.4 not work?

yes 23.0.0 up

**Comment by Vera-Firefly** [comment]
> > Does Mesa 23.0.4 not work?
> 
> yes 23.0.0 up

Then use it. Your device doesn't support Mesa24.0.x
