### ISSUE TITLE
请修改curseforge_api_key的信息

### ISSUE THREAD

**Issue by root-S7** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#172]
### Describe the bug

这个API是用于访问curseforge上整合包的。
但是，所有第三方打包的启动器这个API返回值都是"DUMMY"。
若不修改将会导致在线搜索整合包功能失效

### The log file and images/videos

![image](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/110681414/36aebac5-ffe6-4413-a019-de028b17f7ad)

### Steps To Reproduce

```markdown
修改该API的文件在PojavLauncher/app_pojavlauncher/build.gradle
```

**Comment by Vera-Firefly** [comment]
![Screenshot_2024_0324_152037](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/abd77bb1-ec7a-49ff-87ce-3035b96fbd63)
你确定?????

**Comment by Vera-Firefly** [comment]
![Screenshot_2024_0324_152253](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/3958817e-8d51-40f1-9b3e-0a680d5bebca)
它的处理在这里,如果你提供了CFK(CurseForgeApiKey)它会替换默认值'DUMMY',否则返回'DUMMY'
这个CFKey是要你自己配备的
我不能直接将CFK写在所有人可见的地方,这是属于个人的CF Api Key
否则会出现滥用现象

**Comment by root-S7** [comment]
> ![Screenshot_2024_0324_152253](https://private-user-images.githubusercontent.com/87926662/316291940-3958817e-8d51-40f1-9b3e-0a680d5bebca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjYxNDYsIm5iZiI6MTcxMTI2NTg0NiwicGF0aCI6Ii84NzkyNjY2Mi8zMTYyOTE5NDAtMzk1ODgxN2UtOGQ1MS00MGYxLTliM2UtMGE2ODBkNWJlYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA3MzcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjdmZmRhOTc4MDI3MTI3ZGQ2Y2I4NWU3NjU0NzQwMzc0NmI1OTUwMGNhMzE1ZjliYjFiZGYyNjMzZmEzMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fj8g6-QzXppK-9yoYrzuL9BAmksERU-9r_6HTw7xfDc) 它的处理在这里,如果你提供了CFK(CurseForgeApiKey)它会替换默认值'DUMMY',否则返回'DUMMY' 这个CFKey是要你自己配备的 我不能直接将CFK写在所有人可见的地方,这是属于个人的CF Api Key 否则会出现滥用现象

对是我看错了，我还以为没有修改

**Comment by root-S7** [comment]
> ![Screenshot_2024_0324_152253](https://private-user-images.githubusercontent.com/87926662/316291940-3958817e-8d51-40f1-9b3e-0a680d5bebca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjYxNDYsIm5iZiI6MTcxMTI2NTg0NiwicGF0aCI6Ii84NzkyNjY2Mi8zMTYyOTE5NDAtMzk1ODgxN2UtOGQ1MS00MGYxLTliM2UtMGE2ODBkNWJlYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA3MzcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjdmZmRhOTc4MDI3MTI3ZGQ2Y2I4NWU3NjU0NzQwMzc0NmI1OTUwMGNhMzE1ZjliYjFiZGYyNjMzZmEzMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fj8g6-QzXppK-9yoYrzuL9BAmksERU-9r_6HTw7xfDc) 它的处理在这里,如果你提供了CFK(CurseForgeApiKey)它会替换默认值'DUMMY',否则返回'DUMMY' 这个CFKey是要你自己配备的 我不能直接将CFK写在所有人可见的地方,这是属于个人的CF Api Key 否则会出现滥用现象

但是我要提醒一下，这个apk如果没有加密情况下还是能翻出来api是多少。
比如：
![Screenshot_20240324_153906_MT Manager](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/110681414/3d212bcd-d12d-440f-9d5b-5d66c3896ec8)

**Comment by Vera-Firefly** [comment]
啊?

**Comment by Vera-Firefly** [comment]
你从哪里翻到的?

**Comment by root-S7** [comment]
> 你从哪里翻到的?

编译后的strings.xml文件内

**Comment by Vera-Firefly** [comment]
看到了

**Comment by Vera-Firefly** [comment]
就这样吧,反正这个东西没多少人用

**Comment by Vera-Firefly** [comment]
这个申请又不难,可以说只要想要,申请一次就有
