### ISSUE TITLE
You have so bad manners> This is for fix JDK 21 and run it perfectly hope you like it sister

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#177]
> This is for fix JDK 21 and run it perfectly hope you like it sister

Another useless spam commit

_Originally posted by @FrostNovaHD in https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/173#issuecomment-2019424891_

**Comment by kjjjjjjjjjjjj** [comment]
I have a issue she have so bad manners you need to say something say with respect

**Comment by kjjjjjjjjjjjj** [comment]
I just want to make a good relation with everyone

**Comment by WesleyVanNeck** [comment]
> ```
>           > This is for fix JDK 21 and run it perfectly hope you like it sister
> ```
> 
> Another useless spam commit
> 
> _Originally posted by @FrostNovaHD in [#173 (comment)](https://github.com/Vera-Firefly/Pojav-Glow-Worm/pull/173#issuecomment-2019424891)_

Well you think your helping but Github ci yml does nothing

**Comment by WesleyVanNeck** [comment]
Idk if my manners are bad it's useless commit

**Comment by kjjjjjjjjjjjj** [comment]
Oh hello dear sister I need to create a relationship with everyone and a good relationship not like bad if you no gift to help so fine and yeah I love your foldcraft launcher and yeah please be cool and be like a sister for me

**Comment by kjjjjjjjjjjjj** [comment]
I am not this respecting you if you have any problem for me tell me and discussed and clear the problem may Allah bless you

**Comment by kjjjjjjjjjjjj** [comment]
I know my coding is nothing but if you do to help me to give help no give the negative comments sister I need to be nice with you and you need to be nice with me there are some problem so clear with me

**Comment by WesleyVanNeck** [comment]
> I know my coding is nothing but if you do to help me to give help no give the negative comments sister I need to be nice with you and you need to be nice with me there are some problem so clear with me

What you did is not even coding

**Comment by kjjjjjjjjjjjj** [comment]
Yes I know sister

**Comment by kjjjjjjjjjjjj** [comment]
I need to friend with you a best friend with you you here with you the first time I see your account I need to talk and friendship with you but you are not interesting in friendship

**Comment by kjjjjjjjjjjjj** [comment]
In foldcraft launcher I like this repository and project so much I want to be in this project but if I don't have clearance with a creator so how can I fit in tell me about do you have a clarity about our friendship

**Comment by kjjjjjjjjjjjj** [comment]
Answer me and tell me

**Comment by WesleyVanNeck** [comment]
> In foldcraft launcher I like this repository and project so much I want to be in this project but if I don't have clearance with a creator so how can I fit in tell me about do you have a clarity about our friendship

Your a stranger your not a friend

**Comment by kjjjjjjjjjjjj** [comment]
Yeah I am not your friend but you need to be friendship with another persons and I need to friendship with you sister do you have a clarity about this issue

**Comment by kjjjjjjjjjjjj** [comment]
Where did you go

**Comment by kjjjjjjjjjjjj** [comment]
And please do clarity about this

**Comment by kjjjjjjjjjjjj** [comment]
Sorry about all the drama and if you need to talk with me so talk with me if you need no to talk with me so no talk with me
