### ISSUE TITLE
Opengl erorr invalid operation 1282

### ISSUE THREAD

**Issue by Rsool22** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#180]
### Describe the bug

Huge fps drop from 300-150 to 7 or 11 when i move this doesn't happen on fold Craft or official pojav only on pojav glow worm especially on the latest update anyone know how to fix it ?

https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/159971646/f16a0096-de7b-4708-a21a-1a131a806048

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Poco x3 pro
- CPU architecture: snap dragon 870 adreno 650
- Android version: Android 13
- PojavLauncher version: 20240322
```

### Anything else?

.

**Comment by Vera-Firefly** [comment]
Fuck your display GL error!!!
This is caused by Optifine. Do not come to the launcher to submit the ISSUES!!!!!

**Comment by Vera-Firefly** [comment]
It's a question of humility, FCL and PojavLauncherTeam are both using things that are too old, and Pojav Glow Worm is using Java and some things that are ahead of both of them
