### ISSUE TITLE
Loading chunks is broken

### ISSUE THREAD

**Issue by ArmanIOL** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#184]
### Describe the bug

When playing Minecraft 1.20.4, regardless of whether it is Sodium or Vanilla, problems appear with loading the chunk, the original PojavLauncher does not have this problem

### The log file and images/videos

![Screenshot_2024-04-04-00-07-28-73_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/f39e420d-f695-40da-96a5-0e2e33210252)

### Steps To Reproduce

```markdown
1. I log into my server
2. I'm waiting for the game to load instantly
3. I'm walking around the world, looking, maybe it can be fixed, but no
```

### Platform

```markdown
- Device model: OnePlus Nord CE2
- CPU architecture: Arm64
- Android version: 12
- PojavLauncher version: any build
```

### Anything else?

Do not write that SODIUM IS NOT SUPPORTED! I had the same problem in vanilla Minecraft

**Comment by ArmanIOL** [comment]
Here are more screenshots with this problem.
![Screenshot_2024-04-04-01-04-51-90_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/dc406a68-8937-42f9-8031-06fc0c694dcb)
![Screenshot_2024-04-04-01-03-55-48_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/641b38a5-96ca-43fd-9e7d-71311724afd9)
![Screenshot_2024-04-04-01-05-05-14_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/2ef32f46-e34f-40d0-8802-2e2e8005431e)
![Screenshot_2024-04-04-01-05-08-11_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/a01fa7be-559e-47a3-8116-e96efc285856)
![Screenshot_2024-04-04-01-05-13-87_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/22ecd612-dd8e-486b-a625-104a393daf3d)
![Screenshot_2024-04-04-01-06-45-95_17cb7ab6fc51aa8e1057d5c882513c52](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/99141319/2802503e-fbd1-4254-aa33-a66f652f5e51)

**Comment by ZiMeng-Firefly** [comment]
You can use the older Java, and this problem comes from the Java that comes with the launcher.
The Java used by Pojav Glow·Worm is too new

**Comment by ArmanIOL** [comment]
> You can use the older Java, and this problem comes from the Java that comes with the launcher. The Java used by Pojav Glow·Worm is too new

I am using the Java provided by me, which version should I use? I use Java 17, but I don’t know which 17 to install.

**Comment by ZiMeng-Firefly** [comment]
> > You can use the older Java, and this problem comes from the Java that comes with the launcher. The Java used by Pojav Glow·Worm is too new
> 
> I am using the Java provided by me, which version should I use? I use Java 17, but I don’t know which 17 to install.

https://github.com/Vera-Firefly/android-openjdk-autobuild

**Comment by ZiMeng-Firefly** [comment]
If you are using Sodium, then this cannot be solved. Sodium is not humble to Pojav.

**Comment by ArmanIOL** [comment]
> If you are using Sodium, then this cannot be solved. Sodium is not humble to Pojav.

I have already stopped using sodium, it can be used with pojavlauncher, but the FPS is several times worse than with Optifine. But thanks for sending me the link to the autobuild

**Comment by Vera-Firefly** [comment]
> > If you are using Sodium, then this cannot be solved. Sodium is not humble to Pojav.
> 
> I have already stopped using sodium, it can be used with pojavlauncher, but the FPS is several times worse than with Optifine. But thanks for sending me the link to the autobuild

so the problem is java, right???

**Comment by ArmanIOL** [comment]
> > > If you are using Sodium, then this cannot be solved. Sodium is not humble to Pojav.
> > 
> > 
> > I have already stopped using sodium, it can be used with pojavlauncher, but the FPS is several times worse than with Optifine. But thanks for sending me the link to the autobuild
> 
> so the problem is java, right???

I don’t know, I use a regular launcher now, but I can say that on Optifine I have 60 fps 9 chunks xd.
