### ISSUE TITLE
无法启动24w14potato

### ISSUE THREAD

**Issue by FiCn7430** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#187]
java.lang.NumberFormatException: For input string: "24w14potato"
	at java.lang.Integer.parseInt(Integer.java:797)
	at java.lang.Integer.parseInt(Integer.java:915)
	at net.kdt.pojavlaunch.profiles.ProfileLanguageSelector.getLanguage(ProfileLanguageSelector.java:240)
	at net.kdt.pojavlaunch.profiles.ProfileLanguageSelector.languageChangers(ProfileLanguageSelector.java:261)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:363)
	at net.kdt.pojavlaunch.MainActivity.lambda$initLayout$4$net-kdt-pojavlaunch-MainActivity(MainActivity.java:212)
	at net.kdt.pojavlaunch.MainActivity$$ExternalSyntheticLambda15.isReady(Unknown Source:6)
	at net.kdt.pojavlaunch.MinecraftGLSurface.lambda$realStart$1$net-kdt-pojavlaunch-MinecraftGLSurface(MinecraftGLSurface.java:612)
	at net.kdt.pojavlaunch.MinecraftGLSurface$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Vera-Firefly** [comment]
需要java21

**Comment by Vera-Firefly** [comment]
Pojav是可以运行最新快照的,不过Mojang那边最新版本快照现在要求最低使用java21
你还是多关注一下论坛消息再来这里提交问题吧

**Comment by MovTery** [comment]
@mc7430 请问你当前的Pojav Glow Worm版本号是？我们需要确认一些东西

**Comment by FiCn7430** [comment]
用的就是java21

**Comment by FiCn7430** [comment]
![Screenshot_2024-04-06-12-46-17-04_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/213793d4-5df6-48ac-9e46-a6442042a4e7)

![Screenshot_2024-04-06-12-46-24-27_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/3b361047-a3a9-4b60-b978-a82fa328ad1d)
![Screenshot_2024-04-06-12-46-27-82_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/5c6616df-b4bd-4693-aaa7-d8baee778bd3)

![Screenshot_2024-04-06-12-46-31-67_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/f8eb80d2-7f3f-4fb2-a45e-a083a613d3e1)

**Comment by FiCn7430** [comment]
但24w14a可以启动![Screenshot_2024-04-06-12-46-47-61_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/a40e61c5-52a4-4ad1-8595-214784a1e6fc)

![Screenshot_2024-04-06-12-47-42-03_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/b9673868-17c9-490d-80a6-994322c220c3)

**Comment by FiCn7430** [comment]
还有一个，在完成创建游戏配置后，点击启动游戏，游戏图标会被错误的放大![Screenshot_2024-04-06-12-53-18-64_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/d6958025-110f-4d91-b229-0ef6884370e1)

**Comment by Vera-Firefly** [comment]
这个特性在最新的测试包中修了,你可以使用这个 https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8572373466

**Comment by MovTery** [comment]
@mc7430 请尝试使用这个构建版本之后的版本
https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8556040111  
由于先前的版本检测逻辑有问题，可能导致此问题的发生，现在我已经更换了检测逻辑，请使用最新版本测试是否还有这类情况发生

**Comment by FiCn7430** [comment]
有一个不知道算不算bug，在游戏配置中选择的Java版本会与实际使用的不符，例如24w16a在配置中选择使用Java8但在游戏中调试界面会发现使用的还是Java21![Screenshot_2024-04-06-12-54-21-96_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/82710077/0e85f825-573d-4f4e-8346-415919db52e4)

**Comment by FiCn7430** [comment]
知道了

**Comment by FiCn7430** [comment]
知道了
