### ISSUE TITLE
无法启动24w14potato(上一个议题我可能没有表述清楚）

### ISSUE THREAD

**Issue by FiCn7430** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#188]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/187

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8572373466
使用这个链接里面的app-release-arm64
