### ISSUE TITLE
[Add] VirGL: Update to Mesa23.2.1 and 24.0.5

### ISSUE THREAD

**Issue by Natthakritp** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#197]
### Describe the bug

Added Mesa VirGL versions 23.2.1 and 24.0.5.
May support OpenGL 4.6 and better performance.

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
-
```

### Anything else?

-

**Comment by Vera-Firefly** [comment]
It is on the agenda and is expected to be updated to Mesa24.1.0 with a number of bug fixes

**Comment by WesleyVanNeck** [comment]
> It is on the agenda and is expected to be updated to Mesa24.1.0 with a number of bug fixes

When do you start working on it again

**Comment by Vera-Firefly** [comment]
> > It is on the agenda and is expected to be updated to Mesa24.1.0 with a number of bug fixes
> 
> When do you start working on it again



> > It is on the agenda and is expected to be updated to Mesa24.1.0 with a number of bug fixes
> 
> When do you start working on it again

Start on next month

**Comment by Natthakritp** [comment]
We are waiting for VirGL Mesa 24.1.0 with excitement.

**Comment by Vera-Firefly** [comment]
I've given up on updating virgl now ,I need to wait for someone more competent to fix vtest before I can continue to update it.
