### ISSUE TITLE
[Add] < msm freedreno support >

### ISSUE THREAD

**Issue by WesleyVanNeck** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#199]
some devices use msm instead of kgsl for freedreno

**Comment by kjjjjjjjjjjjj** [comment]
Nice idea by the way

**Comment by Vera-Firefly** [comment]
test this: https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8958645933

**Comment by kjjjjjjjjjjjj** [comment]
Thank you dear sister I am in this chat because I facing the same problem so thank you

**Comment by Vera-Firefly** [comment]
try it https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/9724146354

**Comment by WesleyVanNeck** [comment]
@Vera-Firefly  check your discord I found some stuff about msm
