### ISSUE TITLE
Dear sister I need your help with this launcher BUG

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#202]
The Android version is 14
Android/data/pojavlauncher.net is not working I can't open it is I can apply modes in this launcher help me and I love your launcher to use and I love your repository to dear sister may god bless you

**Comment by Vera-Firefly** [comment]
The problem isn't with the Launcher itself, you need to give your file manager permission to open it.

**Comment by kjjjjjjjjjjjj** [comment]
Okay thank you my dear sister
