### ISSUE TITLE
Creating an Optifine Profile doesn't work

### ISSUE THREAD

**Issue by 44cK3r** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#210]
I click on which version I want and it downloads what it needs to then the instance starts itself but it doesn't ever seem to do anything just a black screen with a completely different on screen control layout than the default one and the one I made and an FPS Counter that barely changes I don't know if I'm doing anything wrong sorry

**Comment by Vera-Firefly** [comment]
Can you provide a log file?

**Comment by 44cK3r** [comment]
> Can you provide a log file?

![Screenshot_2024-05-07-14-59-00-18_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/86052117/ebf134ec-46ad-465a-a528-9b21de363e7f)

![Screenshot_2024-05-07-14-59-05-74_405a2fc07b254ef5ee3229f4fec175cf.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/86052117/45d1516b-5318-4696-9f6c-df4604c2f78a)

![latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/15229624/latestlog.txt)

Hopefully this helps thank you

**Comment by Vera-Firefly** [comment]
Please use java8 to install optifine
Or check your Internet links

**Comment by 44cK3r** [comment]
> Please use java8 to install optifine
> Or check your Internet links

Ok thank you so very much

**Comment by Vera-Firefly** [comment]
> > Please use java8 to install optifine
> > Or check your Internet links
> 
> Ok thank you so very much

So is it solved?

**Comment by 44cK3r** [comment]
> > > Please use java8 to install optifine
> > > Or check your Internet links
> > 
> > Ok thank you so very much
> 
> So is it solved?

I'll have to check in the morning sorry

**Comment by 44cK3r** [comment]
> > > Please use java8 to install optifine
> > > Or check your Internet links
> > 
> > Ok thank you so very much
> 
> So is it solved?

It seems to work thank you so very much but when it launches automatically the first time where it used to be just a black screen it now shows the menu that would normally be used to install OptiFine but then the instance crashes (not the app) and it shows up in the instance selector so I select it and it seems to launch fine and it seems to have installed fine thank you so very much
