### ISSUE TITLE
Make Zink render support SEUS & Continuum shader like Mali GPUs.

### ISSUE THREAD

**Issue by azurawrtata** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#217]
There's a old Zink renderer (23.0.4 git-7cc0c4e18d) which can run Seus & Continuum shader on my old phone (Snapdragon 888/Adreno660). But after i upgrade to my new phone (Snapdragon8Gen2/Adreno740) the app keep crashing. 

Most Mali GPUs support almost all shaders compared to Adreno but for Adreno 740 , i think its strong enough to run these shaders ( I run Nostalgia v5 max setting and got 20-30fps). 

This one can run Seus & Continuum.
![IMG_20240515_203657](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/85455216/a9a3a5e4-9cf7-41c2-98e4-3727d723845b)

This one cant. 
![IMG_20240515_203752](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/85455216/52badc47-5623-44ed-849a-4b301e387bef)

They both have same Zink version (23.0.4) but the git ver are different. Also newer Zink cant either (24.0.6/24.0.7)

Is there are reason for this?

**Comment by azurawrtata** [comment]
Info : My previous phone is Sharp Aquos R6 (Android 13)
My current phone is OnePlus Ace 3 (Android 14)

**Comment by Vera-Firefly** [comment]
I used the original Mesa 3D content, not the modfiled version
This needs to be solved by the developers of Mesa 3D
Or wait until one day I find a way to fix it

**Comment by azurawrtata** [comment]
Can u try make the modified work on newer Snapdragon soc? Since it's only works on older Snapdragon soc. I know im asking alot but i would appreciate it if u can.

**Comment by Vera-Firefly** [comment]
> Can u try make the modified work on newer Snapdragon soc? Since it's only works on older Snapdragon soc. I know im asking alot but i would appreciate it if u can.

I'll try

**Comment by azurawrtata** [comment]
Thank you , looking forward!
