### ISSUE TITLE
[BUG] 和沉浸工程模组有关的渲染错误  Rendering error related to the Immersive Engineering mod

### ISSUE THREAD

**Issue by Hamakaze1s** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#223]
### Describe the bug

和原版Pojav一样，在使用Holy GL4ES时，安装沉浸工程时会出现类似X-ray的渲染错误。
游戏版本是1.16.5，沉浸工程是最新版的5.1.0-148
尝试更换渲染器的结果如下：
vgpu： 启动时Mojang界面花屏
zink：渲染错误

有解决方法吗？

### The log file and images/videos

GL4ES与zink
[Screenshot_2024-05-24-15-23-56-068_net kdt pojavlaunch firefly](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/50857024/863a11f0-07f7-42dd-88dc-8139ecfac363)
vgpu
[Screenshot_2024-05-24-15-21-59-070_net kdt pojavlaunch firefly](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/50857024/cbc9a00a-d2c4-4d9d-b1c9-7f1ef33ab773)

[latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/15428572/latestlog.txt)

### Steps To Reproduce

```markdown
1.启动Pojav
2.加载或新建存档
3.正常进入世界，但是渲染错误
```

### Expected Behavior

正常渲染

### Platform

```markdown
- Device model: Xiaomi Mi 14
- CPU architecture: Snapdragon 8Gen3
- Android version: 14
- PojavLauncher version: edelweiss-202-0501-10a744d-exp_v3
```

**Comment by Vera-Firefly** [comment]
关闭区域渲染

**Comment by Vera-Firefly** [comment]
![Screenshot_2024-05-24-14-40-39-955_net kdt pojavlaunch firefly](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/d01181b7-06a1-4f6d-bb38-4119f877ff45)

**Comment by Hamakaze1s** [comment]
谢谢回复
性能设置的菜单是某个mod或者部分版本才有的吗
似乎没找到
![IMG_20240524_154940](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/50857024/30fe7374-7f1f-43e8-b554-c8379fb13477)
![IMG_20240524_154924](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/50857024/9a818832-f344-4752-adbd-b1b8dab02cdf)

**Comment by Hamakaze1s** [comment]
装了optifine后，区域渲染默认为关闭，但仍然出现渲染错误，尝试开关区域渲染无效
![Screenshot_2024-05-24-16-32-12-227_net kdt pojavlaunch firefly](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/50857024/efd72469-12b9-4615-8211-8c83484a8b7e)
![Screenshot_2024-05-24-16-32-16-188_net kdt pojavlaunch firefly](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/50857024/af697d2b-c9e0-46f3-9d07-0f3cb200e922)

**Comment by Vera-Firefly** [comment]
麻烦给一下崩溃日志

**Comment by Vera-Firefly** [comment]
> 麻烦给一下崩溃日志

如果会用启动器内置Terminal的话给一下启动器日志

**Comment by Hamakaze1s** [comment]
日志指的是以下这个吗？
游戏本体没有崩溃，所以似乎没有崩溃日志

[latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/15431496/latestlog.txt)

**Comment by Vera-Firefly** [comment]
不受支持的模组,请联系模组开发者
