### ISSUE TITLE
[Enhancement]Add new theme, the current style is really strange and feels boring

### ISSUE THREAD

**Issue by Nekongawi** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#225]
### Describe the bug

Please change the theme of the menu so that it looks better now. It's really boring

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Baca Di atas
```

### Expected Behavior

improve performance, change the file directory / device memory / games if on android-data-pojav it's really complicated 

### Platform

```markdown
- Device model: Realme C31
- CPU architecture: (forget)
- Android version: 11
- PojavLauncher version: edelweis exp3
```

### Anything else?

add new features for Optimizer/Improve performance

**Comment by Vera-Firefly** [comment]
You can try [Pojav Zenith Horizon](https://github.com/HopiHopy/PojavZenithHorizon), and we're going to merge the repositories
