### ISSUE TITLE
[BUG] Sodium Patcher it does not work

### ISSUE THREAD

**Issue by AnonymoDGH** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#232]
### Describe the bug

I have tried to use the Sodium patcher several times in different versions and it never works well and Sodium crashes when entering a world

### The log file and images/videos

Nothing

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: Samsung A03 
- CPU architecture: Arm64 
- Android version: 13
- PojavLauncher version: Pojav.Beta.Zink.20231224-lwarlip_v3
```

**Comment by Vera-Firefly** [comment]
Please make sure that your version corresponds to the patch version

**Comment by Vera-Firefly** [comment]
It is also important to note that Sodium does not support for Pojav

**Comment by Vera-Firefly** [comment]
It is also important to note that Sodium does not support for Pojav

**Comment by Vera-Firefly** [comment]
It is also important to note that Sodium does not support for Pojav
