### ISSUE TITLE
[BUG] Sodium patcher not working x2

### ISSUE THREAD

**Issue by AnonymoDGH** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#234]
### Describe the bug

Sodium simply does not work for me in any version of pojav flow worn

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15604466/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav
open world
and crash
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: Samsung A03
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: all if glow worn
```

**Comment by Vera-Firefly** [comment]
Please make sure that your version corresponds to the patch version

**Comment by Vera-Firefly** [comment]
It is also important to note that Sodium does not support for Pojav
