### ISSUE TITLE
新鸿蒙使用自定义游戏文件位置时无法拉取权限

### ISSUE THREAD

**Issue by kwssdme** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#236]
设备 huawei nova 5z
系统 harony OS 3.0..0.165 aosp10
版本 最新165

**Comment by MovTery** [comment]
@kwssme 如果你第一次使用软件申请权限，且拒绝了权限，那么鸿蒙会记住你的选择，以后所有的申请都会被拒绝，自己前往设置手动开启权限

**Comment by kwssdme** [comment]
> @kwssme 如果你第一次使用软件申请权限，且拒绝了权限，那么鸿蒙会记住你的选择，以后所有的申请都会被拒绝，自己前往设置手动开启权限

但是在权限设置里缺没有存储权限![Screenshot_20240610_231336_com.android.permissioncontroller.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/94110828/e88c54e0-1db7-4ca9-952f-01659e338bbd)

就像这样

**Comment by Vera-Firefly** [comment]
> > @kwssme 如果你第一次使用软件申请权限，且拒绝了权限，那么鸿蒙会记住你的选择，以后所有的申请都会被拒绝，自己前往设置手动开启权限
> 
> 但是在权限设置里缺没有存储权限![Screenshot_20240610_231336_com.android.permissioncontroller.jpg](https://private-user-images.githubusercontent.com/94110828/338244075-e88c54e0-1db7-4ca9-952f-01659e338bbd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODE2MTgsIm5iZiI6MTcxODA4MTMxOCwicGF0aCI6Ii85NDExMDgyOC8zMzgyNDQwNzUtZTg4YzU0ZTAtMWRiNy00Y2E5LTk1MmYtMDE2NTllMzM4YmJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA0NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YzIyY2ExZDIxYjBiMzUxZTRiODYwNTFmOGY3NzNhZGFhNTA1NTk3MDZlYmU2ZDYyOTRjOWNmZTRmZWUyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FAR_jZlQ7jwYjZHEyiAuU1v2NFIzEOVBXYAG6iuLm0s)
> 
> 就像这样

这里不会有的,你一开始没同意是你的问题

**Comment by Vera-Firefly** [comment]
你可以进入你的
```
隐私与安全->其它权限->特殊权限设置->所有文件访问权限
```
开启

**Comment by kwssdme** [comment]
特殊权限设置里并没有或许adb命令能得到吧建议做一个权限拉取的页面![Screenshot_20240611_131520_com.android.settings.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/94110828/925df0a6-cd5a-4da8-bf98-4962d394cb1f)

**Comment by routhing** [comment]
疑似故障在安卓10（MIUI12.0.7）复现，找不到Pojavlauncher的储存权限功能。
虽然在安卓10上做修复可能意义不大，但如果能连接到储存外面可以更方便文件整理。

**Comment by routhing** [comment]
疑似故障在安卓10（红米k305gMIUI12末版MIUI12.0.7）复现，找不到Pojavlauncher的储存权限功能。
虽然在安卓10上做修复可能意义不大，但如果能连接到储存外面可以更方便文件整理。

**Comment by kwssdme** [comment]
> 疑似故障在安卓10（红米k305gMIUI12末版MIUI12.0.7）复现，找不到Pojavlauncher的储存权限功能。
> 虽然在安卓10上做修复可能意义不大，但如果能连接到储存外面可以更方便文件整理。

所以这是安卓10的问题？

**Comment by kwssdme** [comment]
在用adb授与所有文件读取权限是会提示Package net.kdt.pojavlaunch.firefly has not requested permission android.permission.READ_EXTERNAL_STORAGE但是在AndroidManifest.xml又能找到
我是个小白不懂安卓开发

**Comment by Vera-Firefly** [comment]
这个问题出在鸿蒙系统的用户默认选择,我们尽量想办法解决

**Comment by kwssdme** [comment]
我重新安装了发现根本没有任何的权限拉取反而这个版本的启动器还被鸿蒙爆病毒了![Screenshot_20240612_140657_com.huawei.security.privacycenter.jpg](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/94110828/bccbfbee-b6d0-49c8-a39c-e21d1fca946c)

**Comment by kwssdme** [comment]
> 这个问题出在鸿蒙系统的用户默认选择,我们尽量想办法解决

鸿蒙那边重新安装会删除之前的权限拉取记录之后再重新生成现在的问题是无法拉取存储权限只要把这个解决就好

**Comment by Vera-Firefly** [comment]
> > 这个问题出在鸿蒙系统的用户默认选择,我们尽量想办法解决
> 
> 鸿蒙那边重新安装会删除之前的权限拉取记录之后再重新生成现在的问题是无法拉取存储权限只要把这个解决就好

![Image_1718202998281](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/2107f9a2-3185-4d22-80c7-1f5d3979190e)
主要问题就是这些了,问题出自鸿蒙系统,如果我们选择解决的话意味着要重写大部分内容.
目前我的项目仅有`UI和实用功能`协作者一个,`虚拟终端`功能的协作者一个,而我是负责`渲染器部分`.
并且我和另外的几个协作者都是业余开发者,而非业余的只负责处理一些我们无法解决的问题.
对于鸿蒙系统的那些东西…已经是我们能力之外的事情了

**Comment by kwssdme** [comment]
我用的不是新鸿蒙用的是安卓套壳的鸿蒙

**Comment by Vera-Firefly** [comment]
> 我用的不是新鸿蒙用的是安卓套壳的鸿蒙

先用着吧,也就无法自定义游戏文件而已,其它功能都是正常的

**Comment by kwssdme** [comment]
那我试着自己修复吧
