### ISSUE TITLE
Pojav魔改的vk0.3.7-v14在APP更新Mesa24.1后不认Turnip驱动，无论是否勾选系统驱动均只认高通官驱

### ISSUE THREAD

**Issue by routhing** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#237]
### Describe the bug

如标题所示

### The log file and images/videos

如标题所示

### Steps To Reproduce

```markdown
如标题所示
```

### Expected Behavior

希望能正常调用驱动版本号，像之前正常调用Turnip24.1.99那样。

### Platform

```markdown
- Device model: k30 5g
- CPU architecture: sdm765g
- Android version: 10（MIUI12.0.7）
- PojavLauncher version: 6月9日更新的release-AArch64不带运行库版本
```

### Anything else?

在这里报告这个issue，如果修复这个问题有困难的话，那目前就先不修复吧
（有玩家应该认识我啦😂😂）

**Comment by routhing** [comment]
There may be friends who read English and need to know the relevant questions:

        The mobile phone is Redmi K30 5G, SoC is SM7250(Snapdragon 765G), Operating System version is Android 10 and MIUI12.0.7, Pojav Glow·Worm version is release-20240609-AArch64-noruntime
﻿
        In the previous Mesa24.0, the VulkanMod still recognize the V24.1.99 of the Turnip-driver. But when the Pojav Glow·Worm Mesa version is updated to 24.1, the VulkanMod0.3.7-v14 will not be recognize the Turnip-driver. That is to say, after upgrading the Mesa from V24.0 to V24.1, no matter whether the switch to “Use the System Driver” is turned on or not, after entering the game, the VulkanMod always recognizes is the official GPU driver of Qualcomm

**Comment by routhing** [comment]
There may be friends who read English and need to know the relevant questions:

The mobile phone is Redmi K30 5G, SoC is SM7250(Snapdragon 765G), Operating System version is Android 10 and MIUI12.0.7, Pojav Glow·Worm version is release-20240609-AArch64-noruntime
﻿
In the previous Mesa24.0, the VulkanMod still recognize the V24.1.99 of the Turnip-driver. But when the Pojav Glow·Worm Mesa version is updated to 24.1, the VulkanMod0.3.7-v14 will not be recognize the Turnip-driver. That is to say, after upgrading the Mesa from V24.0 to V24.1, no matter whether the switch to “Use system Vulkan driver” is turned on or not, after entering the game, the VulkanMod always recognize is the official GPU driver of Qualcomm

**Comment by Vera-Firefly** [comment]
你的日志文件呢?

**Comment by Vera-Firefly** [comment]
> There may be friends who read English and need to know the relevant questions:
> 
> The mobile phone is Redmi K30 5G, SoC is SM7250(Snapdragon 765G), Operating System version is Android 10 and MIUI12.0.7, Pojav Glow·Worm version is release-20240609-AArch64-noruntime ﻿ In the previous Mesa24.0, the VulkanMod still recognize the V24.1.99 of the Turnip-driver. But when the Pojav Glow·Worm Mesa version is updated to 24.1, the VulkanMod0.3.7-v14 will not be recognize the Turnip-driver. That is to say, after upgrading the Mesa from V24.0 to V24.1, no matter whether the switch to “Use system Vulkan driver” is turned on or not, after entering the game, the VulkanMod always recognize is the official GPU driver of Qualcomm

Mesa23.0.4 or something else?
Mesa23.0.4或其它的也是一样的吗?

**Comment by routhing** [comment]
非常抱歉，因为我的疏忽，未先截取日志。且本人未正确反馈issue，私自判断是24.0和24.1的区别，故暂时关闭问题并道歉。浏览日志后推测是该版本的MIUI系统无法调用Turnip驱动导致的，影响VulkanMod和Zink渲染器，FreeDreno正常加载。具体日志报错的有如下：

AdrenoSupp: Failed to load Turnip!
dlopen failed: cannot locate symbol "call_once" referenced by "/data/app/net.kdt.pojavlaunch.firefly.debug-S-L5gfY6SjL5LkyV-XMHWg==/lib/arm64/libvulkan_freedreno.so"...

进一步判断可能需要更深层的日志
