### ISSUE TITLE
[BUG] <Problem with Infinix Smart 8 where I can't use Zink>

### ISSUE THREAD

**Issue by Nekoj09** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#238]
### Describe the bug

![Screenshot_20240616-145543](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/172976991/79ce2ff3-b047-4184-9765-e88f2298b2c6)
The following is an example of when I use Zink render In which case, the screen has an error. I will provide the specifications of my cellphone And I hope this bug can be fixed 

### The log file and images/videos

![Screenshot_20240616-145543](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/172976991/17057ca2-0ff6-4ae5-a6ac-f1f14c6163b3)

### Steps To Reproduce

```markdown
Yes as in the text above and below the problem.
```

### Expected Behavior

I hope that the Infinix Smart 8 can use Zink rendering .I've been using the old version until the newest one and it still doesn't work?!

### Platform

```markdown
- Device model: infinix Smart 8

- CPU architecture: ×1.6 GHz Cortex-A75 and 6×1.6 GHz Cortex-A55 cores,

- Android version: 13

- PojavLauncher version: *I've used all versions of pokav that have zink rendering Including the Glow-Worm version, I have changed Mesa to Pojav but it still doesn't work.*
```

### Anything else?

No.

**Comment by Vera-Firefly** [comment]
Can you provide the log file and the exact version number?

**Comment by Vera-Firefly** [comment]
Can you give me an answer?
