### ISSUE TITLE
[BUG] <mouse bug>

### ISSUE THREAD

**Issue by Zenzctf** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#239]
### Describe the bug

my mouse otg is not support

### The log file and images/videos

...

### Steps To Reproduce

```markdown
start launching the game java my mouse no working
```

### Expected Behavior

mouse error

### Platform

```markdown
- Device model: vivo
- CPU architecture: forget
- Android version: 11
- PojavLauncher version: glow.worm lasted
```

### Anything else?

mouse error

**Comment by Vera-Firefly** [comment]
Provide the following log file
Quit after starting the game once
after enter 
```
nohup /system/bin/logcat > /sdcard/Android/data/$PACKAGE_NAME/files/log.txt &
```
in the built-in terminal

**Comment by Vera-Firefly** [comment]
你是会提交issues的,我3分钟内回复你,等你个回复要等一天是吧?
连个基本的日志都不给,你让天王老子来了也解决不了
不会提交别提交了

**Comment by Vera-Firefly** [comment]
我们开发者的耐心不是无限的,我们开发者的时间也不是特别富裕(甚至可以说基本没时间)
我们开发者尽可能的帮用户解决问题,但是建立在你所提交的建议或者问题给了充足的说明
而不是给个issues就跑人,有考虑过开发者的感受吗?
连最基本的尊重都没有

**Comment by Vera-Firefly** [comment]
补充一句:mouse这一块本就不是我做的,你要像这样子提交issues的话找Pojav团队去,我们不会管像你这种提交issues就跑人的用户
如果你要提交的话请给出充足的条件,比如日志文件或者运行视频/截图等
