### ISSUE TITLE
[Enchancement]: Add more features

### ISSUE THREAD

**Issue by xbxct** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#243]
- [ ] A switch for checking available memory at the start of the game;
- [ ] A switch for displaying a crash message;
- [x] A button for copying/transferring the game from the application to non-isolated storage;
- [x] Plugins to support graphic mods on other renderings, and possibly full-fledged global modifications(Doubt? This may require active adaptation by the mod author);
- [x] Adding scroll wheel to controls. 
- [ ] Expanding and correcting the argument window.
- [ ] Setting up double-clicking the "play" button (if it is not a bug in one of the reports). 
- [ ] Opening the on-screen keyboard when entering into the in-game text bar.
The first 2 points are not fulfilled, the switches are missing.
Postscript: Thank you

**Comment by Vera-Firefly** [comment]
In addition to the fourth point, it has been implemented in [Pojav Zenith Horizon](https://github.com/HopiHopy/PojavZenithHorizon)

**Comment by xboct02** [comment]
Zenith is worse
