### ISSUE TITLE
[BUG] Extremely low gl4es performance 

### ISSUE THREAD

**Issue by shizotoaster** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#244]
### Describe the bug

Gl4es performance is extremely low. I get ~0-1fps even though standard pojav works fine (~60fps)

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15945528/latestlog.txt)

### Steps To Reproduce

```markdown
1. Run the game through gl4es
2. Enjoy the performance (lol)
```

### Expected Behavior

~60fps gameplay 

### Platform

```markdown
- Device model: Xiaomi Mi Mix 3 5g
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Pojav.Glow.Worm-20240622
```

**Comment by Vera-Firefly** [comment]
This seems to be a Java problem. The Java build I'm using here is always up to date. There are some features that I can't interfere with. I'll roll it back to the normal version later

**Comment by shizotoaster** [comment]
I doubt that this is related to java because I use the exact same java build to run standard pojav

**Comment by Vera-Firefly** [comment]
There is no doubt that it is the problem of Java

**Comment by Vera-Firefly** [comment]
try it https://github.com/Vera-Firefly/android-openjdk-build/actions/runs/9629929947

**Comment by shizotoaster** [comment]
Nope, still laggy 
![Screenshot_20240624-082516](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/51480483/de224907-a348-4f5b-9545-0ebc3ad3204d)

**Comment by Vera-Firefly** [comment]
Oh! Adreno! This is caused by the device. You can try to install Optifine or sodium modules to solve this problem.

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/87926662/fde04a43-df4d-4faf-bd32-ea29a9e2fdde
If you use optifine, you also need to turn it open

**Comment by shizotoaster** [comment]
> Oh! Adreno! This is caused by the device. You can try to install Optifine or sodium modules to solve this problem.

But why does that happen? I get better results on the latest gp pojav release
![Screenshot_20240624-084513](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/51480483/a40b958b-424f-49d2-8ec1-e605c2c0f4ef)

**Comment by Vera-Firefly** [comment]
I do not know

**Comment by EvilAlee** [comment]
> > Oh! Adreno! This is caused by the device. You can try to install Optifine or sodium modules to solve this problem.
> 
> But why does that happen? I get better results on the latest gp pojav release ![Screenshot_20240624-084513](https://private-user-images.githubusercontent.com/51480483/342177498-a40b958b-424f-49d2-8ec1-e605c2c0f4ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQ0NDAsIm5iZiI6MTcyMjM0NDE0MCwicGF0aCI6Ii81MTQ4MDQ4My8zNDIxNzc0OTgtYTQwYjk1OGItNDI0Zi00OWQyLThlYzEtZTYwNWMyYzBmNGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyNTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMWY2MGI0ZDg0MTViNTEyN2Q1N2NjZjZlM2RjODg3Mjg3NWYwYzg2ZTVkNzE4MGI2ZWU0YzRlYmI5ZGYwZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PxBLkpHMEJ1sfV_XjbavDeEL2nB5T60Ng3fG9YWuraQ)

What's your render distance, I think this processer can do better.
