### ISSUE TITLE
Hello I find out this site today 

### ISSUE THREAD

**Issue by kedrick021** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#245]
### Describe the bug

How to play 1.18.2 zink Vulcan 

### The log file and images/videos

None

### Steps To Reproduce

```markdown
1. Pojavlauncher glow
2. Version 1.18.2 with zink
3. Crash
```

### Expected Behavior

I hope you can recommend version on Pojavlauncher 

### Platform

```markdown
- Device model: Poco c65
- CPU architecture: 64
- Android version: 14 8gb/250gb
- PojavLauncher version: 20240609
```

### Anything else?

Can you give zink Vulcan for 1.18.2+

**Comment by Vera-Firefly** [comment]
Select Mesa3D, which defaults to zink, and other options are set in the Renderer Experimental Settings

**Comment by kedrick021** [comment]
I already do that still crash on 1.18.2
Mesa 23
Zink Vulcan 

I try on 1.12.2 working pls help I want to play 1.18.2 on zink
