### ISSUE TITLE
[BUG] White Screen On VGPU Render

### ISSUE THREAD

**Issue by AnikyMX** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#250]
### Describe the bug

White screen on VGPU Render

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16043351/latestlog.txt)

### Steps To Reproduce

```markdown
1. Switch Render to VGPU
2. Run Minecraft Version 1.12.2
3. Full White Screen
```

### Expected Behavior

Maybe it can be resolved?

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: Latest (released)
```

**Comment by AnikyMX** [comment]
![Screenshot_2024-06-30-14-02-14-45](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/71912870/83d621f1-bd03-471c-9bde-dae6ac467fbd)

**Comment by Vera-Firefly** [comment]
Go to the Renderer Experimental Settings and try opening the Spare bridge.

**Comment by AnikyMX** [comment]
> Buka Pengaturan Eksperimental Renderer dan coba buka jembatan Spare.

![IMG_20240630_210920](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/71912870/4a30e86e-d529-40b0-a645-cc1a90d8b181)
No change, still white screen

**Comment by Vera-Firefly** [comment]
I don't know, the VGPU renderer has been out of maintenance, and there is no way to solve this problem at present,You can use virgl or zink renderer
