### ISSUE TITLE
把始终抓住鼠标这一功能从强制改成用户可调节

### ISSUE THREAD

**Issue by CloudBack0601** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#253]
Make "always grab the mouse and use the touchpad as the cursor” a functional botton to toggle it

提出这个建议是因为我在用VGA拓展坞连接鼠标的时候发现滑动鼠标时游戏内光标不会动，在20240525的更新中，添加了始终抓住鼠标这一功能，但同时也是导致问题出现的原因，希望可以把始终抓住鼠标这一功能从强制改成用户可调节（毕竟不是所有人都习惯手搓java版）

**Comment by Vera-Firefly** [comment]
那个是捕获鼠标位置的东西,你可以提供一下运行录屏吗?

**Comment by CloudBack0601** [comment]
> 那个是捕获鼠标位置的东西,你可以提供一下运行录屏吗?

https://www.mediafire.com/file/osvum3omt2pngzl/mmexport1720065739994.mp4/file

**Comment by CloudBack0601** [comment]
> > 那个是捕获鼠标位置的东西,你可以提供一下运行录屏吗?
> 
> https://www.mediafire.com/file/osvum3omt2pngzl/mmexport1720065739994.mp4/file

这样的么

**Comment by Vera-Firefly** [comment]
Have you tried updating the launcher?
Latest : https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/9775899007

**Comment by CloudBack0601** [comment]
> Have you tried updating the launcher?
> Latest : https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/9775899007

这个就是最新版的才会有这样的问题啊 20240501的版本就不会

**Comment by Vera-Firefly** [comment]
> > Have you tried updating the launcher?
> > Latest : https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/9775899007
> 
> 这个就是最新版的才会有这样的问题啊 20240501的版本就不会

这部分内容并不是我写的,我负责的是渲染器部分,或许你应该向[PojavLauncher团队](https://github.com/PojavLauncherTeam/PojavLauncher)提交这个问题

**Comment by CloudBack0601** [comment]
> > > Have you tried updating the launcher?
> > > Latest : https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/9775899007
> > 
> > 这个就是最新版的才会有这样的问题啊 20240501的版本就不会
> 
> 这部分内容并不是我写的,我负责的是渲染器部分,或许你应该向[PojavLauncher团队](https://github.com/PojavLauncherTeam/PojavLauncher)提交这个问题

已经给他们交了issue
