### ISSUE TITLE
[BUG] Zink processor not working and mesa 3d crashing

### ISSUE THREAD

**Issue by ilkerpro78** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#274]
### Describe the bug

How do I fix this? When I enter it with zink to open the shader, the game crashes.How can I fix this?
And when I enter Mesa 3D, most shaders give errors and do not work properly. How can I fix this?

### The log file and images/videos

![Screenshot_2024-07-20-07-28-04-972_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/07a032f5-450c-4fce-9d1e-1387a045c4d4)

https://github.com/user-attachments/assets/90679828-26f9-4b27-b147-f4b88195c4b2

### Steps To Reproduce

```markdown
I enter normal settings with zink but it crashes the game, I looked on YouTube and tried all the solutions but it doesn't work.
```

### Expected Behavior

How do I solve this problem please

### Platform

```markdown
- Device model: redmi note 12 pro 5g 
- CPU architecture: mediatek 1080
- Android version: 14
- PojavLauncher version: 20240718
```

### Anything else?

And when I try to download an optifine or forge profile, it gives me the runtime is broken error. How to fix this?

**Comment by Vera-Firefly** [comment]
Can you provide a log file?

**Comment by ilkerpro78** [comment]
> Bir günlük dosyası sağlayabilir misiniz?

How

**Comment by Vera-Firefly** [comment]
I can't help you solve this problem without log file

**Comment by ilkerpro78** [comment]
> Günlük dosyası olmadan bu sorunu çözmenize yardımcı olamam

I need to share my daily log file with you?

**Comment by Vera-Firefly** [comment]
> > Günlük dosyası olmadan bu sorunu çözmenize yardımcı olamam
> 
> I need to share my daily log file with you?

I'm referring to your game crash log

**Comment by ilkerpro78** [comment]
> > > Günlük dosya olmadan bu sorunu çözmenize yardımcı olamam
> > 
> > 
> > Günlük kayıt dosyamı sizinle paylaşmam gerekiyor?
> 
> Oyun çökme günlüğüne atıfta bulunuyorum

Can you please tell me how to get the log file?

**Comment by ilkerpro78** [comment]
> > > Günlük dosya olmadan bu sorunu çözmenize yardımcı olamam
> > 
> > 
> > Günlük kayıt dosyamı sizinle paylaşmam gerekiyor?
> 
> Oyun çökme günlüğüne atıfta bulunuyorum

I'm sorry, some of the things I said are wrong because I use translation. Could you please explain to me how to obtain the daily log file with a photo or something similar?
