### ISSUE TITLE
Newer Mesa just make the performance worse than previous build

### ISSUE THREAD

**Issue by azurawrtata** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#277]
Is it me or the newer the Mesa is , the laggier it become? Like i thought newer version supposed to be more "optimized or improved" yet it just give big performance drops.  

The only playable Mesa build is either 23.0.4 or 23.0.0-devel to me. 

Device : OnePlus Ace 3
CPU : Snapdragon 8 Gen 2
GPU : Adreno 740

**Comment by azurawrtata** [comment]
This isn't complain but rather than um "confusion" 😂

**Comment by ilkerpro78** [comment]
> Ben miyim yoksa Mesa ne kadar yeniyse o kadar gecikmeli mi oluyor? Ben yeni sürümün daha "optimize edilmiş veya geliştirilmiş" olması gerektiğini düşünüyordum ama sadece büyük performans düşüşleri veriyor.
> 
> Oynanabilir tek Mesa sürümü bana göre 23.0.4 veya 23.0.0-devel.
> 
> Cihaz : OnePlus Ace 3 İşlemci : Snapdragon 8 Gen 2 GPU : Adreno 740

Really me phone redmi note 12 pro 5g and mesa 24.1.4 Not working

**Comment by azurawrtata** [comment]
> > Ben miyim yoksa Mesa ne kadar yeniyse o kadar gecikmeli mi oluyor? Ben yeni sürümün daha "optimize edilmiş veya geliştirilmiş" olması gerektiğini düşünüyordum ama sadece büyük performans düşüşleri veriyor.
> > Oynanabilir tek Mesa sürümü bana göre 23.0.4 veya 23.0.0-devel.
> > Cihaz : OnePlus Ace 3 İşlemci : Snapdragon 8 Gen 2 GPU : Adreno 740
> 
> Really me phone redmi note 12 pro 5g and mesa 24.1.4 Not working

Try use older Mesa build. Newer build kind of buggy and laggy somehow.

**Comment by ilkerpro78** [comment]
> > > Ben miyim yoksa Mesa ne kadar yeniyse o kadar gecikmeli mi oluyor? Ben yeni sürümün daha "optimize edilmiş veya geliştirilmiş" olması rejimim ama sadece büyük performans düşüşleri veriyor. 
> > > Tek Mesa sürümü bana 23.0.4 veya 23.0.0 sürümüne göre oynanabilir. 
> > > Cihaz : OnePlus Ace 3 İşlemci : Snapdragon 8 Gen 2 GPU : Adreno 740
> > 
> > 
> > Gerçekten benim telefonum redmi note 12 pro 5g ve mesa 24.1.4 çalışmıyor
> 
> Eski Mesa yapısını kullanmayı deneyin. Yeni yapı bir şekilde hatalı ve gecikmeli.

At the same time most shaders do not work

**Comment by ilkerpro78** [comment]
> > > Ben miyim yoksa Mesa ne kadar yeniyse o kadar gecikmeli mi oluyor? Ben yeni sürümün daha "optimize edilmiş veya geliştirilmiş" olması rejimim ama sadece büyük performans düşüşleri veriyor. 
> > > Tek Mesa sürümü bana 23.0.4 veya 23.0.0 sürümüne göre oynanabilir. 
> > > Cihaz : OnePlus Ace 3 İşlemci : Snapdragon 8 Gen 2 GPU : Adreno 740
> > 
> > 
> > Gerçekten benim telefonum redmi note 12 pro 5g ve mesa 24.1.4 çalışmıyor
> 
> Eski Mesa yapısını kullanmayı deneyin. Yeni yapı bir şekilde hatalı ve gecikmeli.

What version of mesa do you recommend?

**Comment by Vera-Firefly** [comment]
The problem stems from the driver and Mesa itself, and 24.1.x will theoretically have significant optimizations and fix most bugs.But it seems to limit your frame rate.
