### ISSUE TITLE
[BUG] <Short description>When you open the version with Forge, the loading screen becomes black

### ISSUE THREAD

**Issue by ilkerpro78** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#278]
### Describe the bug

When you download Forge and open it to install a mod, the loading screen goes black.

### The log file and images/videos

![image0](https://github.com/user-attachments/assets/9a440045-dac3-4676-8504-ca77d43fd6f5)

### Steps To Reproduce

```markdown
I didn't do anything or use a mod with zink and this is what happened.
```

### Expected Behavior

Please tell me something or bring an update to fix this bug

### Platform

```markdown
- Device model: redmi note 12 pro 5g 
- CPU architecture: mediatek 1080
- Android version: 14
- PojavLauncher version:20240718
```

### Anything else?

Also, when I open Mesa 3D to play shaders with the mod and enter the game, the game freezes and does not start.

**Comment by Vera-Firefly** [comment]
This is a known problem that only occurs in this loading interface and does not affect usage

**Comment by ilkerpro78** [comment]
> Bu, yalnızca bu yükleme arayüzünde oluşan ve kullanımı etkilemeyen bilinen bir sorundur

So, is normal pojavlauncer or pojavlauncer glow worm better?
