### ISSUE TITLE
[BUG] <Short description>1.21 fabric is faulty

### ISSUE THREAD

**Issue by ilkerpro78** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#279]
### Describe the bug

When I enter Fabric in 1.21 and open the world, the world appears corrupted and it cannot be fixed. How can I fix it?

### The log file and images/videos

![Screenshot_2024-07-24-18-14-32-503_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/6e5c1bab-b2c1-4a26-82b1-732d2984bc9b)

### Steps To Reproduce

```markdown
I added a few mods to prevent game lag in 1.21 fabric and it looks like this, but there is no such error in normal pojavlauncer.
```

### Expected Behavior

Please tell me how to fix this error

### Platform

```markdown
- Device model:redmi note 12 pro 5g 
- CPU architecture:mediatek 1080
- Android version:14
- PojavLauncher version:20240718
```

**Comment by DonutEpicuS** [comment]
are you using a 32 bit or 64 bit OS?

**Comment by Vera-Firefly** [comment]
Can you provide the log file?

**Comment by ilkerpro78** [comment]
> Log dosyasını sağlayabilir misiniz?

How

**Comment by Vera-Firefly** [comment]
> > Log dosyasını sağlayabilir misiniz?
> 
> How

![Screenshot_2024-07-27-15-41-42-531_net kdt pojavlaunch firefly debug-edit](https://github.com/user-attachments/assets/9a619ba9-8638-43ed-a8e8-b8592151004d)

**Comment by DonutEpicuS** [comment]
is 1.21 running on java 21 -32bit or 64 bit?

**Comment by Vera-Firefly** [comment]
> is 1.21 running on java 21 -32bit or 64 bit?

64bit

**Comment by DonutEpicuS** [comment]
did you change any settings or they're default?

**Comment by ilkerpro78** [comment]
> herhangi bir ayarı değiştirdin mi yoksa varsayılan ayarlar mı?
No, I didn't change any settings. Then I changed it again and logged in

**Comment by Vera-Firefly** [comment]
Out of Question Time/No Log

**Comment by Vera-Firefly** [comment]
Out of Question Time/No Log
