### ISSUE TITLE
[Zink vulkan renderer crashes] <Zink vulkan don't works .>

### ISSUE THREAD

**Issue by Shulker02** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#280]
### Describe the bug

Regardless of the version I enter, the game ends up closing after a moment, even though I don't have any mods  :(

### The log file and images/videos

https://github.com/user-attachments/assets/4e1e3549-a3a9-414c-9c1a-457ddd787266

### Steps To Reproduce

```markdown
:(
```

### Expected Behavior

I can't use shaders anymore because of this crash bug

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 14
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by Vera-Firefly** [comment]
Dude, this isn't Pojav Glow·Worm

**Comment by Vera-Firefly** [comment]
Providing your log file may solve the problem.

**Comment by Shulker02** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16378420/latestlog.txt)
If it's the wrong file, correct me :)
