### ISSUE TITLE
[BUG] game stuck on loading terrain 1.21

### ISSUE THREAD

**Issue by DonutEpicuS** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#281]
### Describe the bug

I've been trying to play pojav 1.21 for several weeks by now but the game just won't load
i use java21 on 32bit ★★★
when i load up the game the "mojang" loading screen is now my panarama and when i click on other buttons the tabs selected become the panarama
but this is not the main issue, after a couple minutes the normal tricky trials panarama appears, now back to the point when i want to join a world of a server it always ALWAYS gets stuck on the "loading terrain" screen, and after a couple minutes it just decides to crash

### The log file and images/videos

this is the panarama glitch
![Screenshot_2024-07-27-03-15-22-287_net kdt pojavlaunch](https://github.com/user-attachments/assets/7459680f-f534-420a-9cc4-2f30c3e746aa)
![Screenshot_2024-07-27-03-15-31-504_net kdt pojavlaunch](https://github.com/user-attachments/assets/2f3b8db6-a3e1-4163-b095-94ec73236542)
this is the loading terrain one 
![Screenshot_2024-07-27-03-16-25-256_net kdt pojavlaunch](https://github.com/user-attachments/assets/064b43c7-94e2-4dbd-9322-34013ed73fc8)

### Steps To Reproduce

```markdown
1.open pojavlauncher -java21 32bit
2.wait for game to load
3. join/create a world/server
4.get stuck on loading terrain screen
5. get a crash after 10 minutes
```

### Expected Behavior

i expected the game to open and definitely not crash

### Platform

```markdown
- Device model: Xiaomi -Redmi 9C
- CPU architecture: arm32
- Android version: 10
- PojavLauncher version: fuchsia main v3
```

### Anything else?

im using :
holy Gl4es- java21 (32bit) -on 64 it crashes
900 mb ram allocated (it crashes if i go higher)

**Comment by aaaapai** [comment]
Please send latestlog.txt

**Comment by aaaapai** [comment]
@DonutEpicuS Hello,Try this Java runtime.
[jre21-aarch32](https://github.com/aaaapai/android-openjdk-build/actions/runs/10174535011/artifacts/1758666804)

**Comment by ghost** [comment]
No it's a bug with 32-bit system in newer update. It's cannot fix because not compatible with 32-bit system
