### ISSUE TITLE
Panfrost(Mesa24.1.4) is broken on Mali-G710

### ISSUE THREAD

**Issue by WesleyVanNeck** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#282]
### Describe the bug

try panfrost

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16402764/latestlog.txt)

### Steps To Reproduce

```markdown
start with panfrost
```

### Expected Behavior

panfrost should start

### Platform

```markdown
- Device model: google pixel 7
- CPU architecture:  aarch64
- Android version: 15
- PojavLauncher version: latest
```

**Comment by Vera-Firefly** [comment]
Mali G710 is not supported by Panfrost (Mesa24.1.4)

**Comment by Vera-Firefly** [comment]
You can use 23.0.0-devel

**Comment by WesleyVanNeck** [comment]
> Mali G710 is not supported by Panfrost (Mesa24.1.4)

yes but why did you add unknown suppoer to it

**Comment by WesleyVanNeck** [comment]
> You can use 23.0.0-devel

ahh yes the slow ass one

**Comment by Vera-Firefly** [comment]
> > Mali G710 is not supported by Panfrost (Mesa24.1.4)
> 
> yes but why did you add unknown suppoer to it

Some devices may be able to use it

**Comment by EvilAlee** [comment]
Panfrost not starting,
Mali-610 mp3,
Any Fix.

**Comment by WesleyVanNeck** [comment]
> Panfrost not starting, Mali-610 mp3, Any Fix.

@Vera-Firefly

**Comment by ghost** [comment]
Mali-G610 is supported for panfrost need to fix (for G71 writes in under it's not supported)




![Screenshot_2024-08-09-14-57-41-680_com android chrome-edit](https://github.com/user-attachments/assets/3e839337-fbaf-4978-933e-ca042fb5d848)

**Comment by ghost** [comment]
I don't know is any different between mali G71 and mali G710

**Comment by Vera-Firefly** [comment]
> Mali-G610 is supported for panfrost need to fix (for G71 writes in under it's not supported)
> 
> ![Screenshot_2024-08-09-14-57-41-680_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/356576942-3e839337-fbaf-4978-933e-ca042fb5d848.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTU1NjMsIm5iZiI6MTcyMzIxNTI2MywicGF0aCI6Ii8xNDA0NjUyNjYvMzU2NTc2OTQyLTNlODM5MzM3LWZiYWYtNDk3OC05MzNlLWNhMDQyZmI1ZDg0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNDU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWQ0ZGY5MDg2MmVhMzA2MDI4MjM3YjdiMjAyNjE4NzAyY2UxZjZmMTI1ZGI4ZWM5YjIwNTcwZmQ3ZTk4YzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jC1rMzMAcK8toOWierWCMbQZeztoj-Vn61FUf8Z1Tp0)

Honestly, I don't know.
I don't know much about Panvk.

**Comment by WesleyVanNeck** [comment]
> > Mali-G610 is supported for panfrost need to fix (for G71 writes in under it's not supported)
> > ![Screenshot_2024-08-09-14-57-41-680_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/356576942-3e839337-fbaf-4978-933e-ca042fb5d848.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTU1NjMsIm5iZiI6MTcyMzIxNTI2MywicGF0aCI6Ii8xNDA0NjUyNjYvMzU2NTc2OTQyLTNlODM5MzM3LWZiYWYtNDk3OC05MzNlLWNhMDQyZmI1ZDg0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNDU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWQ0ZGY5MDg2MmVhMzA2MDI4MjM3YjdiMjAyNjE4NzAyY2UxZjZmMTI1ZGI4ZWM5YjIwNTcwZmQ3ZTk4YzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jC1rMzMAcK8toOWierWCMbQZeztoj-Vn61FUf8Z1Tp0)
> 
> Honestly, I don't know. I don't know much about Panvk.

You mean panfrost not panvk

**Comment by EvilAlee** [comment]
> Mali-G610 is supported for panfrost need to fix (for G71 writes in under it's not supported)
> 
> ![Screenshot_2024-08-09-14-57-41-680_com android chrome-edit](https://private-user-images.githubusercontent.com/140465266/356576942-3e839337-fbaf-4978-933e-ca042fb5d848.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjQxODIsIm5iZiI6MTcyMzg2Mzg4MiwicGF0aCI6Ii8xNDA0NjUyNjYvMzU2NTc2OTQyLTNlODM5MzM3LWZiYWYtNDk3OC05MzNlLWNhMDQyZmI1ZDg0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMzA0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmFiNTYzMTNmYzIzYTBjOGNkODhkMjQ1NjY2ZTZkYzRhNDc5ZDllMTNmZDcxNWMxNTFjNWU1YzgzN2JkMTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ifKgeHZApSz9xc91HhlICN2EGZwnt8zIoTn3a28GS28)

But I wasn't able to launch on 610,
By the way 610-710 are similar in structure and layout but latter one has cores support!
