### ISSUE TITLE
[BUG] 1.20.1 Fabric failed to start

### ISSUE THREAD

**Issue by LanRhyme** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#283]
### Describe the bug

权限不足是什么鬼啊？originos和hyperos均出现此问题，一个很神奇的点是用电脑下好资源文件后导入到手机，再将启动器的检查资源文件完整性关闭后原本会出问题的连锁挖掘模组就可以正常使用了，但其他的模组还是会有问题

### The log file and images/videos

[latestlog(1) (1).txt](https://github.com/user-attachments/files/16403785/latestlog.1.1.txt)

### Steps To Reproduce

```markdown
启动游戏
```

### Expected Behavior

我希望可以解决此问题

### Platform

```markdown
- Device model: IQOO Z9 Turbo
- CPU architecture: 骁龙8sgen3
- Android version: Android14
- PojavLauncher version: fuchsia-20240727-18e8924-main_v3
```

**Comment by Vera-Firefly** [comment]
检查你有没有授予启动器所有文件管理权限
还有最好不用从任何其它启动器移植版本到Pojav
Pojav的那个版本检测如果检测不到你用的什么版本会直接启动不了
你可以去下正规的模组整合包导入到Pojav,这样不容易出事

**Comment by LanRhyme** [comment]
> 检查你有没有授予启动器所有文件管理权限
> 还有最好不用从任何其它启动器移植版本到Pojav
> Pojav的那个版本检测如果检测不到你用的什么版本会直接启动不了
> 你可以去下正规的模组整合包导入到Pojav,这样不容易出事

授予所有文件管理权限的列表中没有pojav，hyperos和originos都没有
一开始是直接通过pojav的自动下载下载1.20.1fabric的，但是发现加了模组后无法启动才尝试导入的，这个问题是一位群友出现的，我测试了一下发现我也有这问题

**Comment by Vera-Firefly** [comment]
你可以直接搜索文件和权限这两个字样

**Comment by LanRhyme** [comment]
> 你可以直接搜索文件和权限这两个字样

能找的授予权限的地方，但是列表中只有部分软件，而没有pojav，大概就是这样

**Comment by LanRhyme** [comment]
![ad8becc9cd5fdc36080bd009f13dd105](https://github.com/user-attachments/assets/89e5ed20-94a0-4cce-853e-c9c8c5e31bf1)

**Comment by Vera-Firefly** [comment]
离谱
