### ISSUE TITLE
How to update to lwjgl 3.3.3

### ISSUE THREAD

**Issue by beta-mango** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#284]
Can't launch Minecraft because minimum version of lwjgl is 3.3.3 and I got 3.3.1. How can I update to 3.3.3?

**Comment by beta-mango** [comment]
Found a lwjgl 3.3.3 build

**Comment by EvilAlee** [comment]
> Can't launch Minecraft because minimum version of lwjgl is 3.3.3 and I got 3.3.1. How can I update to 3.3.3?

My bro Can even be found here.😜
