### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by gumen2258** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#287]
### Describe the bug

在使用vulkan zink渲染器的时候，无法启动minecraft

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16549120/latestlog.txt)

Uploading Screenrecorder-2024-08-08-22-12-12-720.mp4…

### Steps To Reproduce

```markdown
使用vulkan zink渲染器时无法进入世界，但是mesa zink就能进入
```

### Expected Behavior

我希望能修复这个问题

### Platform

```markdown
- Device model: Redmi K70E
- CPU architecture: arm 64
- Android version: 14
- PojavLauncher version: fuchsia-20240727-18e8924-main_v3
```

**Comment by Vera-Firefly** [comment]
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G615 MC6) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
你有注意到这个吗?

**Comment by Vera-Firefly** [comment]
你应该更新你的启动器

**Comment by Vera-Firefly** [comment]
最新的是[20240808](https://github.com/Vera-Firefly/Pojav-Glow-Worm/releases/tag/20240808)

**Comment by Vera-Firefly** [comment]
补充一下: 使用Zink在不打开渲染器实验性设置时默认使用的是Mesa最新的正式发行版,它可能不支持你当前的设备,你应该进入 实验性->渲染器实验性设置 选择适合你设备的Mesa版本
大多数设备都可以通过渲染器实验性设置中的内容解决,如果无法解决,那只能是你的 设备/系统 存在问题
或你的设备GPU(/SOC)不在支持的列表内

**Comment by gumen2258** [comment]
> 你应该更新你的启动器

哦噢，三克油
