### ISSUE TITLE
[BUG] gl4es ptitseb doesn't work

### ISSUE THREAD

**Issue by ghost** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#288]
### Describe the bug

I will try to use gl4es ptitseb 3.3 it's crash in 1.21.1 but I try 1.12.2 it's work perfectly. It's related to Vgpu?

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16597119/latestlog.txt)
Latestlog.txt

[latestcrash.txt](https://github.com/user-attachments/files/16597122/latestcrash.txt)
Latestcrash.txt

### Steps To Reproduce

```markdown
1:start pojav glow worm
2:go to renderers
3:set renderer to gl4es ptitseb 3.3
4:start Minecraft
5:exit with code 1
```

### Expected Behavior

.

### Platform

```markdown
- Device model: poco f5 12/256gb
- CPU architecture: aarch64
- Android version: 14
- PojavLauncher version: latest pojav glow worm release
```

### Anything else?

Gpu is adreno 725

**Comment by Vera-Firefly** [comment]
GL4ES Ptitseb is missing a lot of things, and the PojavLauncherTeam doesn't publish "Holy" source code, so GL4ES Ptitseb doesn't run on 1.17 +

**Comment by WesleyVanNeck** [comment]
> GL4ES Ptitseb is missing a lot of things, and the PojavLauncherTeam doesn't publish "Holy" source code, so GL4ES Ptitseb doesn't run on 1.17 +

Uhh you can Chery pick it easily I will look adding it

**Comment by ghost** [comment]
I tested holy gl4es and gl4es ptitseb 3.3 and after 5 times test each of them and my comment is there is no different between of them propably. With gl4es ptitseb 3.3 gave me +2 fps more than holygl4es. The maximum fps in holygl4es if I look an location without any move is 85 fps with gl4es ptitseb 3.3 maximum fps if I look an same location in Minecraft i tested with holygl4es without any move is 87 fps. After I enter the world in Minecraft wait 10 minutes for record maximum fps can renderers get. Minecraft version tested is 1.12.2 without any mod

**Comment by kasrarouhi** [comment]
It's just a comment About gl4es ptitseb 3.3

**Comment by ghost** [comment]
> > GL4ES Ptitseb is missing a lot of things, and the PojavLauncherTeam doesn't publish "Holy" source code, so GL4ES Ptitseb doesn't run on 1.17 +
> 
> Uhh you can Chery pick it easily I will look adding it

Thanks
