### ISSUE TITLE
[BUG]  The screen flickers when in the nether

### ISSUE THREAD

**Issue by Flame2555** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#289]
### Describe the bug

When i enter the nether, the screen starts flickering. In OptiFine 1.20.6.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16605272/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher 
2. Open a world
2. Go to the nether
```

### Expected Behavior

I exepact that the screen will not flicker in the nether again

### Platform

```markdown
- Device model: Infinix Smart 8
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: fuchsia-20240807-9c9be9b-main_v3
```

**Comment by Vera-Firefly** [comment]
The problem may come from Optifine, if not, the problem may come from "vtest" if it's okay to switch to another renderer
Either way, it can't be fixed
