### ISSUE TITLE
[BUG] optifine and forge doesn't install (fabric and quilt work)

### ISSUE THREAD

**Issue by ghost** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#290]
### Describe the bug

I wanna install optifine or forge on any Minecraft version it's crashes. It's not happen on pojav launcher but fabric and quilt work perfecty

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16644610/latestlog.txt)
Latestlog.txt
.
.
.
https://github.com/user-attachments/assets/9d9f24bf-c5e1-4010-bd80-1e49bc0464eb

### Steps To Reproduce

```markdown
1:go to pojav glow worm
2:click on create new profile
3:click on create optifine/forge profile
4:select any optifine/forge version
5:and click on download
6:crash
```

### Expected Behavior

.

### Platform

```markdown
- Device model: poco f5 12/256gb
- CPU architecture: aarch64
- Android version: 14. Android 15 coming soon on my phone
- PojavLauncher version: latest version of pojav glow worm
```

### Anything else?

I turned off quit launcher but still doesn't work

**Comment by Vera-Firefly** [comment]
https://github.com/user-attachments/assets/a3b1cabf-57af-4215-b79a-f75d797b78d5

But, why i can use?

**Comment by Vera-Firefly** [comment]
Maybe you need to update your launcher again.

**Comment by ghost** [comment]
I fix this it's because of -XX:+UseVectorCmov argument I add. in pojav launcher I didn't add this argument and for this pojav launcher didn't crash with forge/optifine. Very sorry for bothering you
