### ISSUE TITLE
[FYI] Adreno 7xx-blob bug

### ISSUE THREAD

**Issue by thejudge156** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#291]
### Describe the bug

Howdy,

I work on QuestCraft. We were made aware of your repo recently and peeked at your Zink stuff. Good job!

This is less of a bug and more a “for your information” report. Basically on Adreno <750 if a certain flag isnt set the same between both drivers, (such as Turnip and Qualcomm), the Android UI flickers due to a bug in the blob. 

Here is the chunk of code that fixed Q3 behavior on 740v3,
`envMap.put("FD_DEV_FEATURES", "enable_tp_ubwc_flag_hint=1"); `

References:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29358#note_2453178
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29754

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

N/A

### Platform

```markdown
N/A
```

### Anything else?

A suggested fix is to find what driver version a phone is and set the environment variable as such, I dont have that data unfortunately.

**Comment by Vera-Firefly** [comment]
Is it related to [This](https://github.com/PojavLauncherTeam/PojavLauncher/pull/5905)?

**Comment by Vera-Firefly** [comment]
Okay, I got it. I'll add it separately

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/10968266878

**Comment by ALADIT20** [comment]
in my phone, when i use zink renderer the ui lobby black(do not appear), the other renderer was fine

**Comment by Vera-Firefly** [comment]
> in my phone, when i use zink renderer the ui lobby black(do not appear), the other renderer was fine

This issues only for Adreno740
If you are another device, please provide log file

**Comment by ALADIT20** [comment]
[latestlog.zip](https://github.com/user-attachments/files/17083593/latestlog.zip)

**Comment by ALADIT20** [comment]
I don't know where to send it because it's my first time using github, the device I'm using is poco F6, Snapdragon 8s gen 3 and adreno 735

**Comment by Vera-Firefly** [comment]
> I don't know where to send it because it's my first time using github, the device I'm using is poco F6, Snapdragon 8s gen 3 and adreno 735

I see you set POJAV_ZINK_PREFER_SYSTEM_DRIVER=1
Attempt to turn off "Allow Zink to use system Vulkan driver"
![1726912552257](https://github.com/user-attachments/assets/1be699a1-db4c-4d4a-b759-048d4ccbc841)

**Comment by ALADIT20** [comment]
> > Saya tidak tahu harus mengirimnya ke mana karena ini pertama kalinya saya menggunakan github, perangkat yang saya gunakan adalah poco F6, Snapdragon 8s gen 3 dan adreno 735
> 
> Saya melihat Anda menyetel POJAV_ZINK_PREFER_SYSTEM_DRIVER=1 Mencoba menonaktifkan "Izinkan Zink menggunakan driver Vulkan sistem" ![1726912552257](https://private-user-images.githubusercontent.com/87926662/369610486-1be699a1-db4c-4d4a-b759-048d4ccbc841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTI5OTcsIm5iZiI6MTcyNjkxMjY5NywicGF0aCI6Ii84NzkyNjY2Mi8zNjk2MTA0ODYtMWJlNjk5YTEtZGI0Yy00ZDRhLWI3NTktMDQ4ZDRjY2JjODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA5NTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMjM0Y2FlZjllNjFhYjk3YTkyZGM2MmZjMjFmYTQ5Y2ZjY2FmMTEwZGQ2ODBjN2M3NDI2NWM1Y2U0ODc3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yzu4BQej0-jD3EoSN_ri5TSSUubPIsMXYsIDSLFKXTM)

thanks its work

**Comment by ALADIT20** [comment]
thanks its work now, when i use playstore version before it was crash when turn off

**Comment by Vera-Firefly** [comment]
> thanks its work now, when i use playstore version before it was crash when turn off

"Pojav Glow·Worm" is not original content, it's another modifiled launcher, and it's not released in the Playstore, only on Github

**Comment by ALADIT20** [comment]
> "Pojav Glow·Worm" is not original content, it's another modifiled launcher, and it's not released in the Playstore, only on Github
>
oh i just found out, i just tried it and in other pojavs it crashed, only this one worked
