### ISSUE TITLE
[BUG] <opengl 3.3.3 crash>

### ISSUE THREAD

**Issue by Faked4040** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#293]
### Describe the bug

Crashing when launch game with gl4es 3.3.3

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16670640/latestlog.txt)

### Steps To Reproduce

```markdown
1. Set gl4es 3.3.3
2. Launch 1.21 vanilla
3. Get crash
```

### Expected Behavior

No

### Platform

```markdown
- Device model: samsung sqp
- CPU architecture: mali G76
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/288
