### ISSUE TITLE
[BUG] Incorrect screen resolution on some devices

### ISSUE THREAD

**Issue by IncludedBerry11** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#294]
### Describe the bug

Devices with a notch (i guess) isn't properly scaled, the mouse is offset(not where it seems) and the screen seems off aswell, it works perfectly with FoldCraft Launcher tho, my device model is vivo 1811

### The log file and images/videos

no

### Steps To Reproduce

```markdown
no
```

### Expected Behavior

I expect the resolution to fit the screen properly and not be offset as done in FoldCraft Launcher

### Platform

```markdown
- Device model: Vivo 1811
- CPU architecture: arm64
- Android version: 8.1
- PojavLauncher version: Pojav ZH latest fork of yours
```

### Anything else?

even the controls seem to be offset

**Comment by Vera-Firefly** [comment]
That doesn't seem right. Have you ever tried full screen?
Press F11 after entering the game

**Comment by ghost** [comment]
I don't know very much about this but try alternate surface rendering off

**Comment by IncludedBerry11** [comment]
here are some more info,
![Screenshot_20240823_064410](https://github.com/user-attachments/assets/f2e0f964-a588-4be0-bf06-4fa12383d503)
[latestlog.txt](https://github.com/user-attachments/files/16720696/latestlog.txt)

**Comment by IncludedBerry11** [comment]
![Screenshot_20240823_064933](https://github.com/user-attachments/assets/aadc3264-629f-4b89-9d13-51aaaf105a65)

**Comment by Vera-Firefly** [comment]
![Screenshot_2024-08-22-23-04-51-500_net kdt pojavlaunch firefly debug](https://github.com/user-attachments/assets/397b23ef-6593-4a52-a7fc-73e6495c65c4)
Did you open it?

**Comment by IncludedBerry11** [comment]
i don't have that option, maybe its for android versions above 8.1?

**Comment by IncludedBerry11** [comment]
it shows 1464x720 in fcl's debug menu but in pojav's debug menu, it shows 1520x720

**Comment by WesleyVanNeck** [comment]
> i don't have that option, maybe its for android versions above 8.1?

You need indeed android 8.1 or higer

**Comment by ghost** [comment]
I recommend not use (ignore notch) option. For saving battery

**Comment by IncludedBerry11** [comment]
can you check and find out what's the problem? it works fine with FCL

**Comment by IncludedBerry11** [comment]
i have tried changing overrideWidth to 1464 and the problem still persists

**Comment by IncludedBerry11** [comment]
it is the same on all pojav launchers

**Comment by IncludedBerry11** [comment]
maybe its only the controls including mouse

**Comment by IncludedBerry11** [comment]
the mouse maybe sends the wrong x-axis coordinates to minecraft?

**Comment by IncludedBerry11** [comment]
> ![Screenshot_2024-08-22-23-04-51-500_net kdt pojavlaunch firefly debug](https://private-user-images.githubusercontent.com/87926662/360723355-397b23ef-6593-4a52-a7fc-73e6495c65c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTAwMDksIm5iZiI6MTcyNDQwOTcwOSwicGF0aCI6Ii84NzkyNjY2Mi8zNjA3MjMzNTUtMzk3YjIzZWYtNjU5My00YTUyLWE3ZmMtNzNlNjQ5NWM2NWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwNDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMDM1ZmUzZTQwYzA5NjQ4NzUxZjMzMGRkMzViNzBhZjMwMzJjY2E1YjQwM2Q4NzAxMDhlMGE2YzA3YzRiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kOrK-gfAct7-dnx9waSZrVzFA0lq4K8V04FoD6BNlZI) Did you open it?

can you convert this fcl code to your pojav's code? this must be the solution

FCL Code :

    public static int getScreenHeight(Context context) {
        WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        Point point = new Point();
        wm.getDefaultDisplay().getRealSize(point);
        return point.y;
    }

    public static int getScreenWidth(Activity context) {
        SharedPreferences sharedPreferences;
        sharedPreferences = context.getSharedPreferences("theme", MODE_PRIVATE);
        boolean fullscreen = sharedPreferences.getBoolean("fullscreen", false);
        WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        Point point = new Point();
        wm.getDefaultDisplay().getRealSize(point);
        if (fullscreen || SDK_INT < Build.VERSION_CODES.P) {
            return point.x;
        } else {
            try {
                Rect notchRect;
                if (SDK_INT >= Build.VERSION_CODES.S) {
                    notchRect = Objects.requireNonNull(wm.getCurrentWindowMetrics().getWindowInsets().getDisplayCutout()).getBoundingRects().get(0);
                } else {
                    notchRect = Objects.requireNonNull(context.getWindow().getDecorView().getRootWindowInsets().getDisplayCutout()).getBoundingRects().get(0);
                }
                return point.x - Math.min(notchRect.width(), notchRect.height());
            } catch (Exception e) {
                return point.x;
            }
        }
    }


Pojav's Code:

    public static DisplayMetrics getDisplayMetrics(Activity activity) {
        DisplayMetrics displayMetrics = new DisplayMetrics();

        if(activity.isInMultiWindowMode() || activity.isInPictureInPictureMode()){
            //For devices with free form/split screen, we need window size, not screen size.
            displayMetrics = activity.getResources().getDisplayMetrics();
        }else{
            if (SDK_INT >= Build.VERSION_CODES.R) {
                activity.getDisplay().getRealMetrics(displayMetrics);
            } else { // Removed the clause for devices with unofficial notch support, since it also ruins all devices with virtual nav bars before P
                activity.getWindowManager().getDefaultDisplay().getRealMetrics(displayMetrics);
            }
            if(!PREF_IGNORE_NOTCH){
                //Remove notch width when it isn't ignored.
                if(activity.getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT)
                    displayMetrics.heightPixels -= PREF_NOTCH_SIZE;
                else
                    displayMetrics.widthPixels -= PREF_NOTCH_SIZE;
            }
        }
        currentDisplayMetrics = displayMetrics;
        return displayMetrics;
    }

**Comment by IncludedBerry11** [comment]
It must be the notch or bounding box and maybe because of ignore notch(which is unaccessible for android 8.1 and below and enabled by default), i have forked and changed MovTery's PojavZenithHorizons's getDisplayMetrics code to minus 66 pixels from displayMetrics.getWidthPixels and it works perfectly fine. please make it so that the ignore notch option is available for all supported android versions if the problem persists on some other devices

**Comment by IncludedBerry11** [comment]
i minus'd 66 pixels because it returns 1464 instead of 1530 which is the correct widthPixels which i have seen in FCL

**Comment by IncludedBerry11** [comment]
nevermind, the bounding rects are implemented unofficially

**Comment by Vera-Firefly** [comment]
Unable to fit all device
