### ISSUE TITLE
[Add] Update LWJGL

### ISSUE THREAD

**Issue by IncludedBerry11** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#295]
The version 3.3.1-snapshot is old and is in the latest version of Pojav, can you try to update it to the latest LWJGL version(3.3.4-snapshot)?

**Comment by xboct02** [comment]
Почему бы не добавить автоматическое обновление комплектующих для приложения?

**Comment by xboct02** [comment]
It looks like you will have to create an additional menu to select the library's weight.

**Comment by xboct02** [comment]
Does the application check the lwjgl3 folder for updated libraries?

**Comment by xbxct** [comment]
> Версия 3.3.1-snapshot старая и находится в последней версии Pojav, можете ли вы попробовать обновить ее до последней версии LWJGL (3.3.4-snapshot)?

Install 3.3.4 linux arm64.zip and move the jar files to pojavlauncher/lwjgl3, but keep in mind that some files may cause a crash or, conversely, degrade performance, check.

**Comment by AnikyMX** [comment]
> > Pada versi 3.3.1-snapshot старая dan находится в последней версии Pojav, mungkin Anda perlu melakukan lebih dari satu kali apakah ada LWJGL (3.3.4-snapshot)?
> 
> Instal 3.3.4 linux arm64.zip dan pindahkan file jar ke pojavlauncher/lwjgl3, tetapi perlu diingat bahwa beberapa file dapat menyebabkan crash atau, sebaliknya, menurunkan kinerja, periksa.

Can it be used on Android?

**Comment by xbxct** [comment]
> > > Pada versi 3.3.1-snapshot старая dan находится в последней версии Pojav, mungkin Anda perlu melakukan lebih dari satu kali apakah ada LWJGL (3.3.4-snapshot)?
> > 
> > 
> > Instal 3.3.4 linux arm64.zip dan pindahkan file jar ke pojavlauncher/lwjgl3, tetapi perlu diingat bahwa beberapa file dapat menyebabkan crash atau, sebaliknya, menurunkan kinerja, periksa.
> 
> Можно ли использовать его на Android?

ths is linux arm

**Comment by xbxct** [comment]
The only disadvantage is the integration, a very small part will work on its own when the launcher turns them on.

**Comment by xboct02** [comment]
It's time to close this issue
