### ISSUE TITLE
Latest fabric 1.21.1 crashes when i install xaeros minimap or Fabric API

### ISSUE THREAD

**Issue by AbyssTamer** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#297]
These are the two mods I only have, but if i play fabric without mods it works, idk what to do

**Comment by AbyssTamer** [comment]
It don't shows any error code

**Comment by AbyssTamer** [comment]
Simply it exit from the app

**Comment by AbyssTamer** [comment]
https://github.com/user-attachments/assets/f26c05c9-b318-4db3-90f9-c06e89165eeb

**Comment by AbyssTamer** [comment]
That is what's happening

**Comment by Vera-Firefly** [comment]
You forget to add ModMenu
and and, Xaero's Map are not supported
