### ISSUE TITLE
Game crashing with vgpu renderer

### ISSUE THREAD

**Issue by rishabha102010** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#300]
### Describe the bug

Whenever I play with vgpu game crashes after showing mojang title screen

### The log file and images/videos

Game crashescwith vgpu renderer iam using mali gpu

### Steps To Reproduce

```markdown
Game crashes with vgpu
```

### Expected Behavior

I thought that renderer runs without crashing

### Platform

```markdown
- Device model: sumsung m32 5g
- CPU architecture: I don't know
- Android version: 11
- PojavLauncher version: verafirefly
```

### Anything else?

Please tell me how to fix this

**Comment by rishabha102010** [comment]
Is anyone there to solve my issue?

**Comment by ghost** [comment]
Vgpu is work up to 1.16.5 meaning you can't play 1.17 and up

**Comment by rishabha102010** [comment]
Ok I understood

**Comment by rishabha102010** [comment]
3
