### ISSUE TITLE
GL4ES pitseb 3.3 doesn't work with 1.17+

### ISSUE THREAD

**Issue by Idkwoeer** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#301]
### Describe the bug

Basically when I chose 3.3 it doesn't work please help

### The log file and images/videos

Dont have

### Steps To Reproduce

```markdown
1.strat 
2.select
3.plau
4.crash
```

### Expected Behavior

I expect it to work 

### Platform

```markdown
- Device model: Motorola 
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: last
```

**Comment by ghost** [comment]
I'm already reported it
#288

**Comment by Idkwoeer** [comment]
> I'm already reported it #288

Actually there may be a bypass

**Comment by ghost** [comment]
Nope. Need a update

**Comment by Idkwoeer** [comment]
> Nope. Need a update

No when 1.17 came out there was a patcher that allowed pojav to work
