### ISSUE TITLE
[BUG] 外置登录无效的会话

### ISSUE THREAD

**Issue by ShulkerSakura** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#303]
### Describe the bug

使用外置登录（littleskin）账户连接使用同一个外置认证服务器的多人游戏时，提示无效的会话，无法使用外置登录进行多人游戏（未关闭认证的）。

### The log file and images/videos

[2024-09-04-1.log.gz](https://github.com/user-attachments/files/16860848/2024-09-04-1.log.gz)

### Steps To Reproduce

```markdown
启动PGW，使用外置登录登录账户，启动游戏，连接使用同样yggdrasil服务器的多人游戏。
```

### Expected Behavior

能够使用外置登录与好友正常联机（不用关闭账户认证或额外安装mod绕过验证）

### Platform

```markdown
- Device model: OnePlus Ace Pro
- CPU architecture: Aarch64
- Android version: 14
- PojavLauncher version: fuchsia-20240903-adf8363-main_v3(9999999)
```

**Comment by ShulkerSakura** [comment]
经不严谨测试，疑似是ClientToken为0导致的问题，从HMCL生成的JSON数据中移植Client Token可以使PGW的外置登录正常通过多人游戏认证。

**Comment by Vera-Firefly** [comment]
有空会看看

**Comment by Vera-Firefly** [comment]
使用这个构建https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/10823516016

**Comment by ShulkerSakura** [comment]
问题未被修复，依旧无效会话

**Comment by Coloryr** [comment]
你的服务器确定使用的是littleskin？
来个服务器IP我进去试试

**Comment by ShulkerSakura** [comment]
是littleskin，ip不方便，+我Q吧
2531493755

**Comment by Coloryr** [comment]
你在群里找一下我，我好友太多了

**Comment by Vera-Firefly** [comment]
> 问题未被修复，依旧无效会话

你服务器有指定用什么启动器吗?

**Comment by ShulkerSakura** [comment]
没有，服务器是自己的，vanilla服务端+authlib-injector

**Comment by ShulkerSakura** [comment]
HMCL PCL FCL均可正常连接

**Comment by ShulkerSakura** [comment]
PGW和PZH不行

**Comment by Vera-Firefly** [comment]
知道原因了.晚点修

**Comment by Vera-Firefly** [comment]
逝世[这个](https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/10832942289)构建

**Comment by Vera-Firefly** [comment]
> 逝世[这个](https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/10832942289)构建

https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/10832942289

**Comment by ShulkerSakura** [comment]
很怪还是无效

**Comment by ShulkerSakura** [comment]
不知道是我操作有问题还是怎么，要不你亲自测试连接我服务器吧，你可以问问coloryr我的服务器地址

**Comment by Coloryr** [comment]
> 不知道是我操作有问题还是怎么，要不你亲自测试连接我服务器吧，你可以问问coloryr我的服务器地址

我已经知道怎么修了，昨天问他谁修，他说他修
