### ISSUE TITLE
[BUG] Unsupported old JWGL. 

### ISSUE THREAD

**Issue by xbxct** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#305]
### Describe the bug

Last versions of sodium get caused crash. 

### The log file and images/videos

[03:07:11] [main/ERROR]: The game failed to start because the currently active LWJGL version is not compatible.

Installed version: 3.3.1 SNAPSHOT
Required version: 3.3.3

You must change the LWJGL version in your launcher to continue. This is usually controlled by the settings for a profile or instance in your launcher.

For more information, please see: https://github.com/Caffeine

### Steps To Reproduce

```markdown
1. Start with sodium.
```

### Expected Behavior

Xx

### Platform

```markdown
- Device model:Readme 10C
- CPU architecture: Qualcomm snapdragon 680
- Android version: 13
- PojavLauncher version: 20240908
Dx
```

### Anything else?

Dx

**Comment by xbxct** [comment]
I apologize for the letter sets, the send button was not pressed.

**Comment by Vera-Firefly** [comment]
In fact, there has always been a lwjgl[3.3.3](https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/10348324325), but I did not use it because of its stability

**Comment by xbxct** [comment]
Mods don't work without support.
