### ISSUE TITLE
[BUG] Unresponsive "Play" button. 

### ISSUE THREAD

**Issue by xbxct** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#306]
### Describe the bug
The "Play" button is triggered the second time.

### The log file and images/videos

https://github.com/user-attachments/assets/d4648a7f-b2ce-4331-b628-d998515d3cea

### Steps To Reproduce

```markdown
1. Press "Play" button.
```

### Expected Behavior

Stable button. 

### Platform

```markdown
- Device model: readme 10c
- CPU architecture: snap 684
- Android version: 13
- PojavLauncher version: 20240908
```

**Comment by Vera-Firefly** [comment]
It looks like your stay is too long, and it's trying to judge as a long press on the button
The "Play" button is judged by clicking and long pressing. Long pressing will skip the download step and start directly

**Comment by xbxct** [comment]
A one-time click just doesn't work

**Comment by xboct02** [comment]
Uploading XRecorder_16092024_132450.mp4…
