### ISSUE TITLE
[BUG] Damaged arguments compilation

### ISSUE THREAD

**Issue by xbxct** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#307]
### Describe the bug
Java does not allow you to insert more than 1 argument at a time. When inserting more, the launcher crashes with an empty log.
### The log file and images/videos

https://github.com/user-attachments/assets/06129f43-f901-4b13-b87b-0e0b6134c6c6

https://github.com/user-attachments/assets/3b8450be-86b8-41cb-9329-a74a6eca367b

### Steps To Reproduce

```markdown
1. Select more than 1 arguments. 
2. Start the pocess. 
```

### Expected Behavior

No crashes. 

### Platform

```markdown
- Device model: Readme10c 
- CPU architecture: snapdragon 680 
- Android version: 13 
- PojavLauncher version: 20240908
```

### Anything else?

1 video - instant insert 
2 video - insert one argument every other time

**Comment by xboct02** [comment]
[Ru] На это как-то вляют аргументы, поэтому это не вожно.

**Comment by xbxct** [comment]
In general, so that the start of the game does not lead to a crash, you need to write one argument at a time by pressing "ok". Everything used to be fine.

**Comment by xboct02** [comment]
![Screenshot_2024-09-16-22-36-35-969_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/690b7a68-43c7-40ce-b0c8-372bd570e170)
Before the crash, all the entered arguments are displayed in the log.
