### ISSUE TITLE
[BUG] <Short description> Sound record

### ISSUE THREAD

**Issue by CIHUYyyy0** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#309]
### Describe the bug

I use the Pojav glow worm, I record it, but why is there no Minecraft sound? Is it a bug or not? While I use another Pojav launcher, it works normally. Please fix it :).

### The log file and images/videos

.p

### Steps To Reproduce

```markdown
I'm recording the POJAV sound but there's no sound
```

### Expected Behavior

?

### Platform

```markdown
- Device model: ITEL P55 5G
- CPU architecture: DIMENSITY 6080
- Android version:13 
- PojavLauncher version: NEW VERSION
```

### Anything else?

Sorry I don't understand, I just filled in a little bit

**Comment by Vera-Firefly** [comment]
Where are your log files?
