### ISSUE TITLE
Sodium 0.5.x Can't used

### ISSUE THREAD

**Issue by Fabzboy** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#312]
### Describe the bug

I'm using fabric 1.21 and test Sodium mod, but when I joined the world in single player...the game immedietly force closed (without any report like code1 / code-1 at all)

How to solve it?

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

Solve the problem, I really want Sodium

### Platform

```markdown
- Device model: vivo y21s
- CPU architecture: 
- Android version: 13
- PojavLauncher version: glow worm latest version
```

**Comment by Vera-Firefly** [comment]
I did not update lwjgl3.3.3
Therefore, the higher version(sodium) cannot be used

**Comment by Fabzboy** [comment]
So, can sodium 0.4.10 for minecrft 1.20.1 work?

**Comment by Fabzboy** [comment]
![Screenshot_2024_0928_132016](https://github.com/user-attachments/assets/22d1849b-8e1d-46ee-b0f5-dc83dad835c0)

Nvm, it does but then this happen...

**Comment by Vera-Firefly** [comment]
> ![Screenshot_2024_0928_132016](https://private-user-images.githubusercontent.com/126932723/371736395-22d1849b-8e1d-46ee-b0f5-dc83dad835c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTY4NjAsIm5iZiI6MTcyNzUxNjU2MCwicGF0aCI6Ii8xMjY5MzI3MjMvMzcxNzM2Mzk1LTIyZDE4NDliLThlMWQtNDZlZS1iMGY1LWRjODNkYWQ4MzVjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDk0YWM1MWQwZjY4ZWZhOWQ5MzViMDZmNDA2ZmVmYjMwMDM3YTNhYzQ5MGVmYWRjOTU4ZWMzYzg4NDk1ZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVn2nR-UYl8X6z3zCfH6KEVnxT6tbxBlEXKoyujNM6k)
> 
> Nvm, it does but then this happen...

Sodium does not support Android…

**Comment by azurawrtata** [comment]
> > ![Screenshot_2024_0928_132016](https://private-user-images.githubusercontent.com/126932723/371736395-22d1849b-8e1d-46ee-b0f5-dc83dad835c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTY4NjAsIm5iZiI6MTcyNzUxNjU2MCwicGF0aCI6Ii8xMjY5MzI3MjMvMzcxNzM2Mzk1LTIyZDE4NDliLThlMWQtNDZlZS1iMGY1LWRjODNkYWQ4MzVjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDk0YWM1MWQwZjY4ZWZhOWQ5MzViMDZmNDA2ZmVmYjMwMDM3YTNhYzQ5MGVmYWRjOTU4ZWMzYzg4NDk1ZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVn2nR-UYl8X6z3zCfH6KEVnxT6tbxBlEXKoyujNM6k)
> > Nvm, it does but then this happen...
> 
> Sodium does not support Android…

It support actually (of course not officially) , i installed bunch if performance mods and there's significant difference in terms of performance.

**Comment by xbxct** [comment]
> > ![Screenshot_2024_0928_132016](https://private-user-images.githubusercontent.com/126932723/371736395-22d1849b-8e1d-46ee-b0f5-dc83dad835c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTY4NjAsIm5iZiI6MTcyNzUxNjU2MCwicGF0aCI6Ii8xMjY5MzI3MjMvMzcxNzM2Mzk1LTIyZDE4NDliLThlMWQtNDZlZS1iMGY1LWRjODNkYWQ4MzVjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDk0YWM1MWQwZjY4ZWZhOWQ5MzViMDZmNDA2ZmVmYjMwMDM3YTNhYzQ5MGVmYWRjOTU4ZWMzYzg4NDk1ZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVn2nR-UYl8X6z3zCfH6KEVnxT6tbxBlEXKoyujNM6k)
> > Nvm, это так, но потом происходит вот что...
> 
> Sodium не поддерживает Android...
Does not support
![Screenshot_2024-10-07-09-43-15-409_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/cbc159ad-35a6-459a-8d0a-59ed98ea7626)

**Comment by ghost** [comment]
> > ![Screenshot_2024_0928_132016](https://private-user-images.githubusercontent.com/126932723/371736395-22d1849b-8e1d-46ee-b0f5-dc83dad835c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTY4NjAsIm5iZiI6MTcyNzUxNjU2MCwicGF0aCI6Ii8xMjY5MzI3MjMvMzcxNzM2Mzk1LTIyZDE4NDliLThlMWQtNDZlZS1iMGY1LWRjODNkYWQ4MzVjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDk0YWM1MWQwZjY4ZWZhOWQ5MzViMDZmNDA2ZmVmYjMwMDM3YTNhYzQ5MGVmYWRjOTU4ZWMzYzg4NDk1ZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVn2nR-UYl8X6z3zCfH6KEVnxT6tbxBlEXKoyujNM6k)
> > Nvm, it does but then this happen...
> 
> Sodium does not support Android…

Sodium actually supported on new update of pojav. They added new renderer called LTW is specially created for sodium and it's actually work

**Comment by xbxct** [comment]
> > > ![Screenshot_2024_0928_132016](https://private-user-images.githubusercontent.com/126932723/371736395-22d1849b-8e1d-46ee-b0f5-dc83dad835c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTY4NjAsIm5iZiI6MTcyNzUxNjU2MCwicGF0aCI6Ii8xMjY5MzI3MjMvMzcxNzM2Mzk1LTIyZDE4NDliLThlMWQtNDZlZS1iMGY1LWRjODNkYWQ4MzVjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDk0YWM1MWQwZjY4ZWZhOWQ5MzViMDZmNDA2ZmVmYjMwMDM3YTNhYzQ5MGVmYWRjOTU4ZWMzYzg4NDk1ZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVn2nR-UYl8X6z3zCfH6KEVnxT6tbxBlEXKoyujNM6k) Nvm, это так, но потом происходит вот что...
> > 
> > 
> > Sodium не поддерживает Android...
> 
> Sodium фактически поддерживается на новом обновлении pojav. Они добавили новый рендер под названием LTW, специально созданный для натрия, и это действительно работает

Everything worked on mesa as well.

**Comment by Vera-Firefly** [comment]
Used by LTW renderer
