### ISSUE TITLE
[UP] Possible/no innovations - 20241117 

### ISSUE THREAD

**Issue by xbxct** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#313]
- [x] ZCG, Shenandoah compatibility.
- [x] Working transparency on the joystick.
- [x] Disable rendering of controls at 0 transparency (if not implemented).
- [x] Returning compatibility with drivers, such as freedreno, as in previous versions (currently crash).
- [x] Improved library support.
- [ ] Expanding the argument window for the visibility of all arguments and the convenience of scrolling. (preferably not in a pop-up manner).
- [x] Elimination of banal errors in the log.
- [x] Fix the crash with the "use vulkan system driver" setting.
- [x] [BUG] There is a performance spike on optimized builds when interacting with the toolbar (mesa/zink).

https://github.com/user-attachments/assets/3a6fc173-ad93-4011-a16e-196fe0de4a15

- [x] The Open gl/es driver.
- [x] Compatible with in-game fullscreen mode.
- [x] Setting the resolution, which varies within smaller limits.
- [x] Extending support for java versions and variations.
- [x] The button still requires a second press, although this is customary.
- [x] Separation of calculation and rendering streams (if it matters).
- [x] Support for custom launcher patches.
- [x] The new LWJGL.
- [x] The ability to send money to the developer.

-20241012-

- [x] Clear the list of valid questions from invalid ones.
- [x] Use the new model gpt in development assistance.
- [ ] Shader shadow support with the LTV render. 
- [x] The driver recognizes and knows how to distinguish the processor from the GPU. This can be considered as a separation of streams.
- [ ] The ability to disable the "Insufficient memory" pop-up window when starting the game.
- [x] Wine and DXVK analysis for rendering (directX).
- [x] Fix incompatibility with 1.21.2(3) of the game (1 frame per second ).
![1000098690](https://github.com/user-attachments/assets/fb1ea335-dd69-4e34-82ff-8b4532f7e2f0)

-20241026-

- [x] Pure pixelation mode, for the sake of performance(unrealizable) .

![1000098407](https://github.com/user-attachments/assets/e39f95cf-de9a-41ef-8b8d-575dc18cb653)

- [x] [BUG] Correction of the ratio of the toolbar control to the toolbar in the game. Occurs when the resolution is changed.

https://github.com/user-attachments/assets/fc844e20-81d7-43f7-a247-2e51ef1d7fdb

- [x] [BUG] Correction of the layout and size of interface elements at a reduced resolution (some go behind the screen).

![1000098402](https://github.com/user-attachments/assets/bfbd8c66-eb4f-47cb-a025-7da19820cca1)
- [x] The permission configured when the game is running is not applied to the permanent setting reset when the game is restarted.

- [ ] [BUG] Sometimes the "Permanent Memory Buffer" and/or "Training Limit" functions are not active in sodium.

-20241117-

- [ ] Ability to automatically update game components.

**Comment by xboct02** [comment]
> ### Describe the bug
> * [ ]  Zxc and other assemblers.
> * [ ]  Working transparency on the joystick.
> * [ ]  No rendering of controls at 0 transparency (if not implemented).
> * [ ]  Returning compatibility with drivers, such as freedreno, as in previous versions.
> * [ ]  Improved library support.
> * [ ]  Expanding the argument window (preferably not in a pop-up manner).
> * [ ]  Elimination of banal errors in the log.
> * [ ]  Fix the crash with the "use vulkan system driver" setting.
> * [ ]  There is a performance spike on optimized builds when interacting with the toolbar.
> * [ ]  The Open gl/es driver.
> * [ ]  Compatible with in-game fullscreen mode.
> * [ ]  Setting the resolution, which varies within smaller limits.
> * [ ]  Extending support for java versions and variations.
> * [ ]  The button still requires a second press, although this is customary.
> * [ ]  Separation of calculation and rendering streams (if it matters).
> * [ ]  Support for custom launcher patches.
> * [ ]  The new LWJGL.
> * [ ]  The ability to send money to the developer.
>   All details are on demand.
> 
> ### The log file and images/videos
> 
> ### Steps To Reproduce
> ```
> -
> ```
> 
> ### Expected Behavior
> 
> ### Platform
> ```
> - Device model: Readme 10C 
> - CPU architecture: Qualcomm snapdragon 680 
> - Android version: 13 
> - PojavLauncher version: 20240927
> ```
> 
> ### Anything else?
> _No response_

**Comment by Vera-Firefly** [comment]
The resolution is customizable. Click on that option

https://github.com/user-attachments/assets/d8c47c44-37d1-4657-a719-089b04f02a10

**Comment by xbxct** [comment]
> Разрешение можно настроить. Нажмите на эту опцию
> 
>  Screenrecorder-2024-10-07-10-47-48-891.mp4

![Screenshot_2024-10-07-09-46-32-611_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/ee4ba90a-4794-41c2-81d4-2f5226887a51)
![Screenshot_2024-10-07-09-49-21-982_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/2a4fe76b-ffdd-4863-b449-091430713ef5)
When you lower the resolution by 20%, the image sharpness is preserved, along with a decrease in load. This is an outdated myth, because a slight change in clarity is still noticeable.

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/11219569639
Fixed a feature that required pressing twice to Launch Game

**Comment by Vera-Firefly** [comment]
> > Разрешение можно настроить. Нажмите на эту опцию
> > Screenrecorder-2024-10-07-10-47-48-891.mp4
> 
> ![Screenshot_2024-10-07-09-46-32-611_net kdt pojavlaunch firefly](https://private-user-images.githubusercontent.com/168722918/374066294-ee4ba90a-4794-41c2-81d4-2f5226887a51.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTgwOTYsIm5iZiI6MTcyODMxNzc5NiwicGF0aCI6Ii8xNjg3MjI5MTgvMzc0MDY2Mjk0LWVlNGJhOTBhLTQ3OTQtNDFjMi04MWQ0LTJmNTIyNjg4N2E1MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNjE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTlhZWY2NDE5NmY5MTU2ZTk4ZDIwYzYyMGI5MmY0Y2E1M2JiMmE5YzUzNzI0NWZmYWU5MWZiMDA2MDU4NTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PYg12ZKSWLN0aVtGDeMD0GVTok3cmn603hAc5cIy2Sw) ![Screenshot_2024-10-07-09-49-21-982_net kdt pojavlaunch firefly](https://private-user-images.githubusercontent.com/168722918/374066369-2a4fe76b-ffdd-4863-b449-091430713ef5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTgwOTYsIm5iZiI6MTcyODMxNzc5NiwicGF0aCI6Ii8xNjg3MjI5MTgvMzc0MDY2MzY5LTJhNGZlNzZiLWZmZGQtNDg2My1iNDQ5LTA5MTQzMDcxM2VmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNjE2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTQyZGNlMDg1NTJjZDJmODlkNDA4OTEzYWY2MTIyZTUzMjhjY2FlYjI1OWNiY2NhOTExMTg5NmE5MDZmNGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sZX2Ez4L14IywEHq4by69Mev54NSM2lZRSxq38y38r0) When you lower the resolution by 20%, the image sharpness is preserved, along with a decrease in load. This is an outdated myth, because a slight change in clarity is still noticeable.

This is a bug and in fact does not allow scaling the resolution below 20%

**Comment by Vera-Firefly** [comment]
Update lwjgl to [3.3.3](https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/11255275506)

**Comment by xboct02** [comment]
The day before yesterday I noticed a real-time resolution setting. I didn't think it was even possible, but I can't even find a word about what contribution you have made.

**Comment by xboct02** [comment]
mesa
![Screenshot_2024-10-15-21-34-07-728_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/47b4ed8e-d9c0-454e-ba1b-5500491d2787)

**Comment by xboct02** [comment]
The performance spike I mentioned:
![Screenshot_2024-10-15-21-34-43-412_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/0a422d12-72d1-4239-990f-898205f1bf05)
![Screenshot_2024-10-15-21-35-01-683_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/b3d9c04a-3093-42a4-a58e-b3c805f1bd40)
The angles are different because it didn't work the first time. As I can guess, either the video memory buffer is cleared, or the application becomes "active". Mesa.

**Comment by xboct02** [comment]
In general, I missed several versions of mesa, which is why the game is so bad. It is worth noting a short-term increase after the slot change in the second picture.

**Comment by xboct02** [comment]
Even when updates are not coming out and users are impatiently waiting for the era of new technologies, Pojav-Glow-Worm gradually reveals its potential, along with QuestCraft™.

**Comment by xbxct** [comment]
I will close the issue if it is no longer being considered.

**Comment by Vera-Firefly** [comment]
> I will close the issue if it is no longer being considered.

Some of the features are less important/not available for user, and those features are no needed by the normal user
This will not be adopted

**Comment by xbxct** [comment]
> > Я закрою этот вопрос, если он больше не рассматривается.
> 
> Некоторые функции менее важны/недоступны для пользователя, и эти функции не нужны обычному пользователю Это не будет принято

thanks

**Comment by xboct02** [comment]
The recent update of chat gpt is available to a wide range of users and is able to improve the performance of the processing of anything.

**Comment by xboct02** [comment]
I will ask you to delete/cross out the garbage tasks.

**Comment by xbxct** [comment]
![Screenshot_2024-11-20-17-53-50-974_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/0f2814b3-42df-478d-8869-d1d7eae5c8c8)
