### ISSUE TITLE
[Question] Performance On Each Runtime Version

### ISSUE THREAD

**Issue by AnikyMX** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#315]
### Describe the bug

Is there a performance difference in each openjdk version?
Internal 8 (1.8.0_432), Is there any performance difference with internal 11 (11.0.25) Or is there a difference with internal 17 (17.0.13), Or is there a difference with internal 21 (21.0.5)

### The log file and images/videos

-

### Steps To Reproduce

```markdown
Run PojavLauncher
```

### Expected Behavior

I hope there is a difference in performance, even though it is not significant

### Platform

```markdown
- Device model: CPH2083
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: Latest
```

**Comment by Vera-Firefly** [comment]
Exists, but is not stable
