### ISSUE TITLE
Add Changelog "Fix White Screen On some devices when using VGPU Render"

### ISSUE THREAD

**Issue by AnikyMX** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#320]
### Describe the bug

After you do the latest update, now the VGPU Render no longer experiences a white screen like the problem https://github.com/Vera-Firefly/Pojav-Glow-Worm/issues/250

### The log file and images/videos

-

### Steps To Reproduce

```markdown
-
```

### Expected Behavior

-

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by xbxct** [comment]
the problem is not common to all devices, so the fix is not valid.
