### ISSUE TITLE
[BUG] <can you add Old List of Mesa 21.0.3 For Zink Rendering?>

### ISSUE THREAD

**Issue by Nekontod** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#321]
### Describe the bug

Here I am using zinc render on pojav glow worm before entering the mojang logo I have already exited the game . Mesa 22 and above does not work on my phone = IE CRASH ON MESA 23 AND ABOVE AND WHITE MENU SCREEN WHEN LIKE TO ENTER THE GAME.I just wish there was a message 21 0 point 3 because that's the only message that works on my phone.

### The log file and images/videos

I don't have a video or picture because I already deleted the forum launcher corner when I had a hard time because I tried it many times,And it's very annoying and weird but I ask the developer to add the old Mesa to the list in the launcher corner or custom Nisa please add Mesa 21.0.3 
I don't have enough funds to buy a new phone so I just asked the developer to add back the old Mesa mesa21.0.3

### Steps To Reproduce

```markdown
Mbuh, what happened was as I explained above, for example like this, this is not just an example, but this is what really happened. I experienced hard on my cellphone at the age of 22 and 23. On my phone when using Zinc render for example I use table 22 I use zinc render when I have entered the menu section or something like that. The menu screen is white  While when I use virgil render in period 22 and I use a little shader I experience transparent screen that has entered the world and also when using shader.So I really hope you can add the old Mesa 21.0.3 back into pojav glow worm
```

### Expected Behavior

Hanya Pesan di atas

### Platform

```markdown
- Device model: Infinix smart 8 
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Actually this only happens on the glowworm pojav launcher
```

### Anything else?

No

**Comment by Vera-Firefly** [comment]
I see your GPU is "Mali-G57 MP1"
Can you provide logs for running Mesa 23.x or 24.x?

**Comment by Nekontod** [comment]
Maybe I can show it when I use Mesa 23.0.0 devel But I have to download pojav glow worm first to display the Crash Log

**Comment by Nekontod** [comment]
And I also need time because the signal in my place is not very supportive.

**Comment by Vera-Firefly** [comment]
![Screenshot_2024-10-17-21-13-33-395_net kdt pojavlaunch firefly debug](https://github.com/user-attachments/assets/17a3f822-d463-4c74-8d75-f02e5b29d2b8)

**Comment by Nekontod** [comment]
Wait

**Comment by Nekontod** [comment]
[latestlog.txt](https://github.com/user-attachments/files/17516054/latestlog.txt)


This is the log from the glow worm pojav.

**Comment by Nekontod** [comment]
(Mesa 22.0.5) 
![Screenshot_20241025-062823](https://github.com/user-attachments/assets/801cbff2-1701-4cb1-8d54-9e11f3a80fcc)
Here I am using the current version of Pojavlauncher Glow Worm.Using Mesa 22.0.5 (Zink)

Mesa 23.0.4 =
![Screenshot_20241025-114640](https://github.com/user-attachments/assets/44e378a7-97ae-441f-b568-d6917c4ffa37)
On this Mesa 23.0.4 I experienced a Black Screen.

**Comment by Nekontod** [comment]
Infinix Smart 8

**Comment by Nekontod** [comment]
@Vera-Firefly Here

**Comment by Vera-Firefly** [comment]
> @Vera-Firefly Here

Your device does not support zink …
try virglrenderer

**Comment by Vera-Firefly** [comment]
Mesa21.0.3 was too old for the new bridging scheme, so I couldn't bring it back

**Comment by Nekontod** [comment]
@Vera-Firefly I use virgl It often happens transparent (Virgl Mesa 22.0.5) 
The reason I use zinc is because of the need to create a shader that works better than virgl

**Comment by Nekontod** [comment]
And I don't have enough money to buy another cellphone because my salary has decreased quite a bit.Can you fix this? Or make a new render other than Virgl I mean Under zink but while virgl but Shader that supports Almost as much as zink I know it all depends on the specs but I need a shader that works for a project of mine too

**Comment by Vera-Firefly** [comment]
But, Mesa21.0.3 do not support new bridge
Is not working

**Comment by Nekontod** [comment]
Hmm btw on my old pojavzink I support playing zink on Mesa 21.0.3 Old zink pojavlauncher

**Comment by Nekontod** [comment]
But I can't access the zinc render The most recent

**Comment by Nekontod** [comment]
@Vera-Firefly

**Comment by Yokiro5943** [comment]
Tôi sử dụng kết xuất zink và bật quay màn hình nó đã bị lỗi khiến màn hình của tôi bị nhấp nháy màu đỏ cuối cùng thì bị đơ không thể thao tác

**Comment by Vera-Firefly** [comment]
You can try to custom Mesa version

**Comment by Yokiro5943** [comment]
> Bạn có thể thử tùy chỉnh phiên bản Mesa

Bạn có thể xin lòng hướng dẫn cho tôi các bước chỉnh sửa được không

**Comment by Vera-Firefly** [comment]
> @Vera-Firefly

Hy, try this: https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/11835178929

Use Custom Mesa Version,then try bridge config 2

**Comment by Nekontod** [comment]
Finally, thank you very much for your response.
