### ISSUE TITLE
[ADD] use SAF to select game storage (for /data)

### ISSUE THREAD

**Issue by qkxkdghkaus** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#322]
I'm using different versions of PojavLauncher. However, they each have a different storage space, android/com.xxx/data/.minecraft, which is inconvenient.
Saf normally can't access files inside data, but the lsposed module no storage restrict allows paths that saf can't give permissions to, so I can match storage with other launchers.
Of course, you can get access to the files under data with root privileges or Shizuku, but the former is a security risk, and the latter requires you to deal with the Shizuku api, so I don't think the extra functionality is worth the effort (though it's nice if you can).
However, for the lsposed module, I think it would be a reasonable feature addition as it requires relatively little time and effort, since the PojavLaunch app only needs to make a saf request, not in a special way.
Thank you for reading

![Screenshot_20241014_184423_Files](https://github.com/user-attachments/assets/19fda48f-9b9d-4149-9e9a-a70161f83700)
이 폴더 사용 means Use this folder (saf)
Translated! sorry for my English skill..

**Comment by Vera-Firefly** [comment]
https://github.com/user-attachments/assets/142f413f-6be3-4489-8994-d01c70c92048

Have you ever tried it?

**Comment by xboct02** [comment]
do you have non-isolated application data storage under saf?

**Comment by xboct02** [comment]
> Screenrecorder-2024-10-19-23-46-19-646.mp4 
> Вы когда-нибудь пробовали?

You have a damaged video, or only I have 0:00.

**Comment by qkxkdghkaus** [comment]
![Screenshot_20241020_130135_Pojav GlowWorm](https://github.com/user-attachments/assets/8ef6d28d-8026-4bc7-a1a8-8119bb73ef59)

Yes, I have tried, but as expected, that path does not access the folder as shown in the picture.
The desired path is /storage/emulated/0/Android/data/net.kdt.pojavlaunch.sol/files, but nothing appears.

The method the app currently uses is the MANAGE_EXTERNAL_STORAGE permission (Manage all files on a storage device), so it can't access /data from other apps by scoped storage.

'Accessing /data with Saf may apply to some Android 10, 11, or magisk/lsposed module users.'

Keyword: SAF Picker

Hope it works for you

**Comment by Vera-Firefly** [comment]
Android's directory access to Android/data is only getting stricter, even with SAF

**Comment by xboct02** [comment]
子既成矣,故成之
