### ISSUE TITLE
Mali-G76 Zink crash

### ISSUE THREAD

**Issue by Awbiwkin** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#323]
### Describe the bug

Only Mesa 22.0.5 works for me, if I put another mesa, then it doesn't even start the game on panforst I have mali-g76 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17521616/latestlog.txt)

### Steps To Reproduce

```markdown
1. Run pojavlauncher 
2. I choose version 1.12.2 Optifine
3. Select the Mesa3d renderer
4. I choose Zink and the latest version of the mesa,
5. Run
At this stage, the flight takes place
```

### Expected Behavior

[hs_err_pid8188.log](https://github.com/user-attachments/files/17521574/hs_err_pid8188.log)

### Platform

```markdown
- Device model: Huawei Nova 5T 6/128G
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest
```

**Comment by Vera-Firefly** [comment]
Try Mesa23.0.4

**Comment by Nekontod** [comment]
@Vera-Firefly Yes, it seems like this problem is almost the same as mine.

**Comment by Awbiwkin** [comment]
> Попробуйте Mesa23.0.4

everything is identical, it crashes the same way, only 22.0.5 works

**Comment by Nekontod** [comment]
@Awbiwkin Do you think he wants to fix it or not?
