### ISSUE TITLE
占满GPU，然后卡死

### ISSUE THREAD

**Issue by mgxhhg** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#325]
### Describe the bug

新版本会突然占满GPU，然后卡住，但之前用旧版PojavLauncher也没问题，一更新就成这样了

### The log file and images/videos

![Screenshot_2024-11-05-13-50-52-223_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/f278896a-05d6-41a2-8710-9b0b083aa4e7)
![Screenshot_2024-11-05-13-50-44-380_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/4b78b83a-836a-4b96-a632-1fb85832b14e)
![Screenshot_2024-11-05-13-50-32-895_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/19ec58f0-5c7b-40fc-bf35-4fa1add36985)
![Screenshot_2024-11-05-13-45-20-023_com miui securitycenter](https://github.com/user-attachments/assets/e830f048-9721-4d57-8e20-cae8a5e8014a)
![Screenshot_2024-11-05-13-25-07-878_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/8bcd9052-a1b7-4d92-9fe6-7bc92185f99f)

### Steps To Reproduce

```markdown
使用zink，先是进入游戏菜单页，还没有开始加载游戏，就突然占满GPU，然后整个屏幕卡住，一会儿又恢复正常，一会儿又开始，进游戏也是这种样子，
```

### Expected Behavior

修复

### Platform

```markdown
- Device model: oculus-mc1.20.1-1.6.15a.jar embeddiumplus-1.20.1-v1.2.12.jar embeddium-0.3.18+mc1.20.1-all.jar
- CPU architecture: 8gen3
- Android version: 14
- PojavLauncher version: fuchsia-20241028-5c5c2fb-main_v3
```

**Comment by Vera-Firefly** [comment]
能否提供一下日志文件?

**Comment by mgxhhg** [comment]
https://drive.google.com/file/d/1NLrJlAhsaOONJ3lSrn7zUrHNLZf4PVYE/view?usp=drivesdk @Vera-Firefly

**Comment by Vera-Firefly** [comment]
你可以直接发在这里,而不是用额外的云盘

**Comment by Vera-Firefly** [comment]
驱动的问题,将在下个版本修复
