### ISSUE TITLE
[BUG] NO SOUND WHEN RECORDING

### ISSUE THREAD

**Issue by ghost** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#328]
### Describe the bug

as that one person said, after recording, the video result do not have any audio, i assume this is a bug, not a settings issue, and if it is, tell us what to do

### The log file and images/videos

no samples

### Steps To Reproduce

```markdown
1. open pojav
2. starts recording
3. saving the vid
4. watching the vid and realizes there's no sound
```

### Expected Behavior

i expect this "bug" to be fixed in the next update.

### Platform

```markdown
- Device model: Tecno Ck7n
- CPU architecture: arm64
- Android version: Android 14
- PojavLauncher version: 20241117
```

**Comment by Jericho346532222233566** [comment]
please respond

**Comment by ghost** [comment]
please respond, heres my log file btw

[latestlog.txt](https://github.com/user-attachments/files/17938538/latestlog.txt)

**Comment by WesleyVanNeck** [comment]
Dublicated of #326
