### ISSUE TITLE
[BUG] <Cannot import mesa drivers>

### ISSUE THREAD

**Issue by system32crowdstrikewin11** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#329]
### Describe the bug

So as usual I was importing some custom mesa drivers but at the moment it says to enter the version name i cannot type any text 

### The log file and images/videos

https://github.com/user-attachments/assets/b9589be1-4486-477d-9a17-8b884bc37a95

### Steps To Reproduce

```markdown
1. Start pojavlauncher 
2. Go to video and renderer
3. Enable experimental exp setup
4. Tap on mesa version 
5. Press on Add buton
6. Choose the file 
7. Enter version name
```

### Expected Behavior

I expected that my keyboard will work and I will be able to type the text but not even the physical keyboard can type the text there 

### Platform

```markdown
- Device model: POCO X6 PRO (Xiaomi 2311DRK48I
- CPU architecture: ARMv9 64 bit
- Android version: Android 14
- PojavLauncher version: fuchsia-20241117-a833e59-main_v3
```

**Comment by Vera-Firefly** [comment]
https://github.com/user-attachments/assets/68b7f5b0-5021-43ba-80f1-fc35cf7577c5
