### ISSUE TITLE
[BUG] <"Shader Rendering Issues on Mesa 24 with Vulkan Backend in PojavLauncher">

### ISSUE THREAD

**Issue by system32crowdstrikewin11** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#331]
### Describe the bug

When running PojavLauncher with Mesa 24 using the Vulkan backend, shaders fail to render properly, resulting in significant visual glitches. This issue is not present in Mesa 23.0.3, where shaders render as expected under the same configuration. However, when shaders are disabled, Mesa 24 performs flawlessly, suggesting the issue is specifically related to how shaders are handled with Mesa 24.

Observations:

1. Mesa 23.0.3 Behavior: Shaders render correctly without any visual issues.

2. Mesa 24 Behavior: Shaders cause graphical artifacts and fail to render properly, leading to a visually broken experience.

3. Without Shaders: Mesa 24 works as intended, with no performance or rendering issues.
4. Possible Cause:

This problem might be linked to the way PojavLauncher interacts with Mesa 24's Vulkan backend. It could be related to missing Vulkan 1.3 extensions in Mesa 24 or discrepancies in how shaders are processed in this version.

### The log file and images/videos

https://github.com/user-attachments/assets/60bec570-15ee-4ec3-bffa-6d105290b4b3

### Steps To Reproduce

```markdown
1. Install PojavLauncher and configure it to use the Vulkan backend.

2. Use a device with mali gpu(e.g mali g615 mc6) with Mesa 24 drivers.

3. Load Minecraft with shaders enabled and observe the rendering issues.

4. Compare the same setup using Mesa 23.0.3, where shaders render correctly.
```

### Expected Behavior

Shaders should render accurately and consistently in Mesa 24, just as they do in Mesa 23.0.3, without any graphical glitches or visual inconsistencies.

### Platform

```markdown
- Device model: POCO X6 PRO
- CPU architecture: ARM64
- Android version: 14
- PojavLauncher version: fuchsia-20241130-7cbd601-main_v3
```

### Anything else?

Request :- Although the issue might stem from Mesa 24's Vulkan implementation, it would be helpful to investigate whether any adjustments or fixes can be made within PojavLauncher to improve compatibility or shader handling with Mesa 24. Even if the root cause lies outside the app, any insight or workaround would be appreciated.

**Comment by Vera-Firefly** [comment]
Mesa24 needs more VK extensions to maintain its functionality, which is usually not supported by the device
So it's needs to be supported by more changes with Mesa
Let's look forward to the subsequent changes!
