### ISSUE TITLE
[Special Thanks] verafirefly for making PGW

### ISSUE THREAD

**Issue by system32crowdstrikewin11** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#332]
### Describe the bug

Back in 2020, I had a dream—a dream to experience ray tracing on mobile. At the time, I was playing Minecraft Pocket Edition and searching for ways to enable RTX. I knew my phone, and even the flagship phones of that era, weren’t capable of supporting ray tracing, but I tried anyway, finding good shaders and hoping for a solution. Eventually, I had to give up, realizing the technology just wasn’t ready.
Fast forward to 2022, a glimmer of hope appeared in the form of PojavLauncher, an app that allowed Java Edition Minecraft to run on mobile. I was excited to finally try shaders, but my phone’s GPU was far too underpowered—it couldn’t run the necessary VirGL or Zink renderers. It felt like I was so close yet so far.
Then came 2024, and things began to change. I got a new phone with better hardware: the POCO X6 Pro, powered by the MediaTek Dimensity 8300 and its Mali-G615 MC6 GPU. Around the same time, the official PojavLauncher introduced the Foxglove update, which brought Mesa 24 and caused crashes due to compatibility issues with Mali GPUs. However, PojavGlow Worm, a fork of PojavLauncher, introduced a game-changing feature: renderer backward compatibility, which allowed me to switch between different Mesa versions. This opened the door to ray tracing on mobile, but the journey wasn’t smooth. I faced over 100 crashes while trying to configure the correct renderer settings in the Pojav Glow Worm section. It took patience, trial, and error, but eventually, I got everything working.
Finally, after years of waiting and persistence, my dream came true. I ran ray tracing on mobile. The feeling was indescribable—pure joy and a sense of accomplishment that words can hardly capture. What once seemed impossible had become my reality.
For this incredible achievement, I want to give special thanks to Vera Firefly, who developed PojavLauncher Glow Worm, making it possible to bypass compatibility issues; MediaTek for crafting the powerful Dimensity 8300 chipset; ARM for creating the Mali G615 MC6 GPU; and Xiaomi for making the POCO X6 Pro available at such an affordable price. Without their contributions, this dream would have remained just that—a dream.
Now, every time I experience ray tracing on my phone, I’m reminded of how far technology has come and how perseverance can turn even the wildest dreams into reality.

### The log file and images/videos

...... 

### Steps To Reproduce

```markdown
....
```

### Expected Behavior

...... 

### Platform

```markdown
- Device model: POCO X6 PRO
- CPU architecture: ARM64
- Android version: 14
- PojavLauncher version: fuchsia-20241130-7cbd601-main_v3
```

### Anything else?

Thanks for making PGW and making my dream come true

**Comment by Vera-Firefly** [comment]
Thanks for supporting PGW
User's support is the greatest motivation for developers!
