### ISSUE TITLE
How do I add a custom turnip mesa 25.0.0?

### ISSUE THREAD

**Issue by beta-mango** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#333]
Can I use [this driver](https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/v25.0.0_r4) in pojav glow worm? If yes, then how can I add it?

**Comment by Vera-Firefly** [comment]
https://github.com/user-attachments/assets/ef34e56a-a7a0-4264-a058-85dd7c226f92

**Comment by Vera-Firefly** [comment]
Custom Turnip Driver is in "Video Settings"

**Comment by beta-mango** [comment]
Thank you very much 😊 
But mesa version is still 24.3.0. Is there no 25.0.0 mesa yet?

**Comment by Vera-Firefly** [comment]
> Thank you very much 😊 But mesa version is still 24.3.0. Is there no 25.0.0 mesa yet?

Turnip: https://github.com/Vera-Firefly/freedreno-auto-builder/actions?query=branch%3Amain
Mesa: https://github.com/Vera-Firefly/Mesa25.0/actions/runs/11946033185
