### ISSUE TITLE
How to add custom mesa

### ISSUE THREAD

**Issue by azurawrtata** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#336]
I wanna install custom meaa version but cant find which type of file it needed.

**Comment by Vera-Firefly** [comment]
look at this - [android-mesa-build](https://github.com/Vera-Firefly/android-mesa-build/actions)
Unzip to the directory you can find and click Import

**Comment by Vera-Firefly** [comment]
https://github.com/user-attachments/assets/3b9a0dda-35eb-4c76-88df-94994765810d
