### ISSUE TITLE
Vulkan mod

### ISSUE THREAD

**Issue by ItsWinterBush** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#337]
can you make it work on pojav glow worm

**Comment by Vera-Firefly** [comment]
![Screenshot_2024-12-23-17-43-00-869_net kdt pojavlaunch firefly debug](https://github.com/user-attachments/assets/4dd4b2cd-9b55-4a82-a81c-808519d5ce96)

**Comment by ItsWinterBush** [comment]
is that patched ?

**Comment by ItsWinterBush** [comment]
can i have your mods folder with vulkan

**Comment by ItsWinterBush** [comment]
can you help me
[latestlog.txt](https://github.com/user-attachments/files/18228092/latestlog.txt)

**Comment by Vera-Firefly** [comment]
[VulkanMod-0.4.5.1.zip](https://github.com/user-attachments/files/18228413/VulkanMod-0.4.5.1.zip)

**Comment by ItsWinterBush** [comment]
> [VulkanMod-0.4.5.1.zip](https://github.com/user-attachments/files/18228413/VulkanMod-0.4.5.1.zip)

thank you 🙏😊

**Comment by azurawrtata** [comment]
> [VulkanMod-0.4.5.1.zip](https://github.com/user-attachments/files/18228413/VulkanMod-0.4.5.1.zip)

Pardon but do you have that worked on 1.21.4? Or is there a tutorial on how to patch it? I can't find any of it 🫠

**Comment by WOOD6563** [comment]
![Image](https://github.com/user-attachments/assets/7211479f-2a58-4b9e-ad1a-c9bcb1c92fd2)
