### ISSUE TITLE
Please create IOS Version

### ISSUE THREAD

**Issue by mzz2345gj** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#338]
Pls this is really live-saving,so create .ipa file so that iPhone users can access this software too

**Comment by Coloryr** [comment]
No plan to support `iPhone`

**Comment by Vera-Firefly** [comment]
No plan to support `iPhone`

**Comment by Vera-Firefly** [comment]
> Pls this is really live-saving,so create .ipa file so that iPhone users can access this software too

We didn't learn the corresponding language and couldn't make some content for IOS
Such as Mesa library

**Comment by mzz2345gj** [comment]
What if I do it?

**Comment by Vera-Firefly** [comment]
> What if I do it?

You can do anything as long as you follow the original project's open source protocols, and anything you do is legal
But if you want to use the name of Pojav Glow·Worm, please add IOS after it and sign it

**Comment by Vera-Firefly** [comment]
We have no plans to make IOS version
