### ISSUE TITLE
Bug vgpu text not visible

### ISSUE THREAD

**Issue by Emanuelfab** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#44]
![Screenshot_20231017-194625](https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/assets/126999818/92b85136-6c0f-49cb-9f3c-7647995d972f)
Please fix these bug

**Comment by Vera-Firefly** [comment]
Are you really sure it's a vgpu renderer and not a virgl renderer?

**Comment by Vera-Firefly** [comment]
This problem with the virgl renderer is not something I can fix, you can get a font fix package from the Pojav team to fix it

**Comment by Emanuelfab** [comment]
![Screenshot_20231018-135825](https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/assets/126999818/f13e1148-7434-49da-b49b-48d2af76c3c0)
Yup am sure it's vgpu renderer

**Comment by Vera-Firefly** [comment]
> ![Screenshot_20231018-135825](https://user-images.githubusercontent.com/126999818/276111895-f13e1148-7434-49da-b49b-48d2af76c3c0.png) Yup am sure it's vgpu renderer

You're not using Pojav Beta,You can go to the Pojav team and ask,https://github.com/PojavLauncherTeam/PojavLauncher/issues/2666
