### ISSUE TITLE
Artifacts do not exist

### ISSUE THREAD

**Issue by hyplant** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#48]
Artifacts do not exist in branch patch-1.
![Screenshot_20231019-190239_Kiwi Browser (Dev)](https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/assets/86937725/42fdb416-7d4b-4d2d-bdac-5d949d7405e4)

**Comment by hyplant** [comment]
Artifacts should appear in github actions.

**Comment by Vera-Firefly** [comment]
> Artifacts should appear in github actions.

I deleted it because it was invalid.You can use this ->https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/actions/runs/6568507355
