### ISSUE TITLE
[BUG] 无法添加认证服务器 Certifications cannot be added

### ISSUE THREAD

**Issue by hsragi** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#80]
### Describe the bug

自己使用blessing skin搭建了一个皮肤站，yggdrasil有配置好，经fcl等启动器测试完全可用，但是在使用这个启动器，添加认证服务器时，提交url后无反应，但统一通行证却可用

### The log file and images/videos

https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/assets/88696336/f01687ba-c9bb-465c-a126-f3e46ee48dd6

### Steps To Reproduce

```markdown
1. 启动“Pojav Beta•Zink”
2. 点击左上角“添加账户”
3. 选择“外置登录”
4. 点击中偏左侧的“+”号
5. 选择“外置登录”
6. 提交api地址（skin.lovepx.team/api/yggdrasil ，各大皮肤站均试过）
7. 无事发生
```

### Expected Behavior

希望能够使用外置登录

### Platform

```markdown
- Device model: 荣耀(Honor) Play5T
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: edelweiss-20231122-489ff59-patch-1
```

**Comment by Vera-Firefly** [comment]
你得确保你提供格式是正确的

**Comment by Vera-Firefly** [comment]
> 你得确保你提供格式是正确的

并且导入的服务器名称不得存在特殊符号

**Comment by Vera-Firefly** [comment]
> > 你得确保你提供格式是正确的
> 
> 并且导入的服务器名称不得存在特殊符号

你可以通过手动更改文件解决

**Comment by Vera-Firefly** [comment]
![Screenshot_2023_1123_185050](https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/assets/87926662/f247d1cd-1741-4442-a0c5-8b4bb1bffb42)
![Screenshot_2023_1123_185152](https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink/assets/87926662/d47daca2-00ed-4e78-846c-38191b86d5ba)
你可以这样去解决

**Comment by Vera-Firefly** [comment]
> ![Screenshot_2023_1123_185050](https://user-images.githubusercontent.com/87926662/285182794-f247d1cd-1741-4442-a0c5-8b4bb1bffb42.png) ![Screenshot_2023_1123_185152](https://user-images.githubusercontent.com/87926662/285182807-d47daca2-00ed-4e78-846c-38191b86d5ba.jpg) 你可以这样去解决

在/storage/emulated/0/Android/data/net.kdt.pojavlaunch.beta/files/servers.json这个位置
