### ISSUE TITLE
使用littleskin外置登录问题

### ISSUE THREAD

**Issue by GuoDong999** [Vera-Firefly/PojavLauncher-Beta-Zink-CN#95]
### Describe the bug

无法获取皮肤
无法加入使用littleskin在线验证的服务器

### The log file and images/videos

none

### Steps To Reproduce

```markdown
1.登录littleskin账号，进入单机存档，不显示自定义皮肤
2.加入使用littleskin在线验证的服务器，提示无效会话
```

### Expected Behavior

none

### Platform

```markdown
- Device model: 红米K70 Pro
- CPU architecture: 骁龙8gen3
- Android version: 14
- PojavLauncher version: 20231201
```

**Comment by Vera-Firefly** [comment]
你有加CSL这个模组吗?
要使离线皮肤加载的话必需要这个模组
服务器的话你要确保你的离线游戏ID在白名单内,否则无法进入

**Comment by Vera-Firefly** [comment]
> 你有加CSL这个模组吗? 要使离线皮肤加载的话必需要这个模组 服务器的话你要确保你的离线游戏ID在白名单内,否则无法进入

CSL(CustomSkinLoader)万用皮肤补丁

**Comment by GuoDong999** [comment]
> 你有加CSL这个模组吗? 要使离线皮肤加载的话必需要这个模组 服务器的话你要确保你的离线游戏ID在白名单内,否则无法进入

服务端使用littleskin并且启用了在线验证，无法加入进服务器，提示无效会话

**Comment by Vera-Firefly** [comment]
> > 你有加CSL这个模组吗? 要使离线皮肤加载的话必需要这个模组 服务器的话你要确保你的离线游戏ID在白名单内,否则无法进入
> 
> 服务端使用littleskin并且启用了在线验证，无法加入进服务器，提示无效会话

听不懂是吧?
你要确保你的客户端装载了CSL和游戏ID在服务器白名单内,否则无效
